from enum import Enum, auto
class HistoryQueryGraphEnums():
    class VerticalAxisTypes(Enum):
        HORIZONTAL_DISPLACEMENT = "HISTORY_QUERY_DISPLACEMENT_X"
        VERTICAL_DISPLACEMENT = "HISTORY_QUERY_DISPLACEMENT_Y"
        HORIZONTAL_VELOCITY = "HISTORY_QUERY_VELOCITY_X"
        VERTICAL_VELOCITY = "HISTORY_QUERY_VELOCITY_Y"
        HORIZONTAL_ACCELERATION = "HISTORY_QUERY_ACCELERATION_X"
        VERTICAL_ACCELERATION = "HISTORY_QUERY_ACCELERATION_Y"
        EFFECTIVE_STRESS_XX = "HISTORY_QUERY_S_X"
        EFFECTIVE_STRESS_YY = "HISTORY_QUERY_S_Y"
        EFFECTIVE_STRESS_XY = "HISTORY_QUERY_S_XY"
        EFFECTIVE_STRESS_Z = "HISTORY_QUERY_S_Z"
        STRAIN_XX = "HISTORY_QUERY_E_X"
        STRAIN_YY = "HISTORY_QUERY_E_Y"
        STRAIN_XY = "HISTORY_QUERY_E_XY"
        EXCESS_PORE_PRESSURE = "HISTORY_QUERY_EXESS_PP"
        # Water
        PORE_PRESSURE = "HISTORY_QUERY_PP"
        HORIZONTAL_HYDRAULIC_VELOCITY = "HISTORY_QUERY_W_FLUX_X"
        VERTICAL_HYDRAULIC_VELOCITY = "HISTORY_QUERY_W_FLUX_Y"
        HORIZONTAL_HYDRAULIC_GRADIENT = "HISTORY_QUERY_W_GRAD_X"
        VERTICAL_HYDRAULIC_GRADIENT = "HISTORY_QUERY_W_GRAD_Y"
        # Temperature
        TEMPERATURE = "HISTORY_QUERY_TEMPERATURE"
        HORIZONTAL_THERMAL_FLUX = "HISTORY_QUERY_H_FLUX_X"
        VERTICAL_THERMAL_FLUX = "HISTORY_QUERY_H_FLUX_Y"
        HORIZONTAL_THERMAL_GRADIENT = "HISTORY_QUERY_H_GRAD_X"
        VERTICAL_THERMAL_GRADIENT = "HISTORY_QUERY_H_GRAD_Y"
        
    class HorizontalAxisTypes(Enum):
        TIME = 9094
        STAGE_LOAD_PERCENTAGE = 9096