from enum import Enum, auto
class BoltTypes(Enum):
	END_ANCHORED = "END_ANCHORED"
	FULLY_BONDED = "FULLY_BONDED"
	QUEENS_CABLE = "QUEENS_CABLE"
	SHEAR_BOLT = "SHEAR_BOLT"
	TIEBACK_BOLT = "TIEBACK_BOLT"
class BulgeTypes(Enum):
	PHASE2_BULGE_GARFORD_25 = "PHASE2_BULGE_GARFORD_25"
	PHASE2_BULGE_NUTCASE_21 = "PHASE2_BULGE_NUTCASE_21"
class SecondaryBondLengthType(Enum):
	P2_BOLT_TIEBACK_SECONDARY_PERCENT = "P2_BOLT_TIEBACK_SECONDARY_PERCENT"
	P2_BOLT_TIEBACK_SECONDARY_PHYSICAL = "P2_BOLT_TIEBACK_SECONDARY_PHYSICAL"
	P2_BOLT_TIEBACK_SECONDARY_FULLY = "P2_BOLT_TIEBACK_SECONDARY_FULLY"
class BoltModels(Enum):
	P2_BOLT_PLASTIC = "P2_BOLT_PLASTIC"
	P2_BOLT_ELASTIC = "P2_BOLT_ELASTIC"
class LinerTypes(Enum):
	P2_LINER_STANDARD_BEAM = "P2_LINER_STANDARD_BEAM"
	P2_LINER_GEOSYNTHETIC = "P2_LINER_GEOSYNTHETIC"
	P2_LINER_REINFORCED_CONCRETE = "P2_LINER_REINFORCED_CONCRETE"
	P2_LINER_CABLE_TRUSS = "P2_LINER_CABLE_TRUSS"
class LinerFormulation(Enum):
	P2_LINER_FORMULATION_BERNOULLI = "P2_LINER_FORMULATION_BERNOULLI"
	P2_LINER_FORMULATION_TIMOSHENKO = "P2_LINER_FORMULATION_TIMOSHENKO"
class MaterialType(Enum):
	ELASTIC = "ELASTIC"
	PLASTIC = "PLASTIC"
class GeometryChoice(Enum):
	LNP_USE_AREA = "LNP_USE_AREA"
	LNP_USE_THICKNESS = "LNP_USE_THICKNESS"
class StaticWaterModes(Enum):
	SWM_PWP = "SWM_PWP"
	SWM_GRID = "SWM_GRID"
class JointTypes(Enum):
	JOINT_NONE = "JOINT_NONE"
	JOINT_MOHR_COULOMB = "JOINT_MOHR_COULOMB"
	JOINT_BARTON_BANDIS = "JOINT_BARTON_BANDIS"
	JOINT_HYPERBOLIC_SIMPLE = "JOINT_HYPERBOLIC_SIMPLE"
	JOINT_MATERIAL_DEPENDENT = "JOINT_MATERIAL_DEPENDENT"
	JOINT_HYPERBOLIC_SOFTENING = "JOINT_HYPERBOLIC_SOFTENING"
	JOINT_DISPLACEMENT_DEPENDENT = "JOINT_DISPLACEMENT_DEPENDENT"
class AdditionalPressureType(Enum):
	JOINT_ADDITIONAL_PRESSURE_BY_VALUE = "JOINT_ADDITIONAL_PRESSURE_BY_VALUE"
	JOINT_ADDITIONAL_PRESSURE_BY_PIEZO = "JOINT_ADDITIONAL_PRESSURE_BY_PIEZO"
class DefineStiffness(Enum):
	DEFINE_PARAMETER = "DEFINE_PARAMETER"
	MATERIAL_DEPENDENT = "MATERIAL_DEPENDENT"
class PileApplicationType(Enum):
	APPLICATION_CONSTANT = "APPLICATION_CONSTANT"
	APPLICATION_BY_LENGTH = "APPLICATION_BY_LENGTH"
class PileEndCondition(Enum):
	FP_NONE = "FP_NONE"
	FP_FORCE = "FP_FORCE"
	FP_DISPLACEMENT = "FP_DISPLACEMENT"
class PileForceApplicationPoint(Enum):
	FP_TOP = "FP_TOP"
	FP_BOTTOM = "FP_BOTTOM"
class PileSkinResistanceType(Enum):
	SKIN_RESISTANCE_ELASTIC = "SKIN_RESISTANCE_ELASTIC"
	SKIN_RESISTANCE_C_PHI = "SKIN_RESISTANCE_C_PHI"
	SKIN_RESISTANCE_LINEAR = "SKIN_RESISTANCE_LINEAR"
	SKIN_RESISTANCE_MULTI_LINEAR = "SKIN_RESISTANCE_MULTI_LINEAR"
	SKIN_RESISTANCE_MATERIAL_DEPENDENT = "SKIN_RESISTANCE_MATERIAL_DEPENDENT"
class PileDefinitionMethod(Enum):
	DISTANCE_FROM_TOP = "DISTANCE_FROM_TOP"
	ELEVATION = "ELEVATION"
class PileConnectionType(Enum):
	CONNECT_FREE = "CONNECT_FREE"
	CONNECT_HINGED = "CONNECT_HINGED"
	CONNECT_RIGID = "CONNECT_RIGID"
	CONNECT_SEMIRIGID = "CONNECT_SEMIRIGID"
class CompositeJointPlacementTypes(Enum):
	BETWEEN_SOIL_ROCK_AND_FIRST_LINER = "BETWEEN_SOIL_ROCK_AND_FIRST_LINER"
	BETWEEN_FIRST_AND_SECOND_LINER = "BETWEEN_FIRST_AND_SECOND_LINER"
	BETWEEN_SECOND_AND_THIRD_LINER = "BETWEEN_SECOND_AND_THIRD_LINER"
	BETWEEN_THIRD_AND_FOURTH_LINER = "BETWEEN_THIRD_AND_FOURTH_LINER"
