from enum import Enum, auto
class BoltTypes(Enum):
	END_ANCHORED = "END_ANCHORED"
	FULLY_BONDED = "FULLY_BONDED"
	QUEENS_CABLE = "QUEENS_CABLE"
	SHEAR_BOLT = "SHEAR_BOLT"
	TIEBACK_BOLT = "TIEBACK_BOLT"
class BulgeTypes(Enum):
	PHASE2_BULGE_GARFORD_25 = "PHASE2_BULGE_GARFORD_25"
	PHASE2_BULGE_NUTCASE_21 = "PHASE2_BULGE_NUTCASE_21"
class SecondaryBondLengthType(Enum):
	P2_BOLT_TIEBACK_SECONDARY_PERCENT = "P2_BOLT_TIEBACK_SECONDARY_PERCENT"
	P2_BOLT_TIEBACK_SECONDARY_PHYSICAL = "P2_BOLT_TIEBACK_SECONDARY_PHYSICAL"
	P2_BOLT_TIEBACK_SECONDARY_FULLY = "P2_BOLT_TIEBACK_SECONDARY_FULLY"
class BoltModels(Enum):
	P2_BOLT_PLASTIC = "P2_BOLT_PLASTIC"
	P2_BOLT_ELASTIC = "P2_BOLT_ELASTIC"
class LinerTypes(Enum):
	P2_LINER_STANDARD_BEAM = "P2_LINER_STANDARD_BEAM"
	P2_LINER_GEOSYNTHETIC = "P2_LINER_GEOSYNTHETIC"
	P2_LINER_REINFORCED_CONCRETE = "P2_LINER_REINFORCED_CONCRETE"
	P2_LINER_CABLE_TRUSS = "P2_LINER_CABLE_TRUSS"
class LinerFormulation(Enum):
	P2_LINER_FORMULATION_BERNOULLI = "P2_LINER_FORMULATION_BERNOULLI"
	P2_LINER_FORMULATION_TIMOSHENKO = "P2_LINER_FORMULATION_TIMOSHENKO"
class MaterialType(Enum):
	ELASTIC = "ELASTIC"
	PLASTIC = "PLASTIC"
class GeometryChoice(Enum):
	LNP_USE_AREA = "LNP_USE_AREA"
	LNP_USE_THICKNESS = "LNP_USE_THICKNESS"
class StaticWaterModes(Enum):
	SWM_DRY = "SWM_DRY"
	SWM_PWP = "SWM_PWP"
	SWM_RU = "SWM_RU"
	SWM_PIEZO = "SWM_PIEZO"
	SWM_GRID = "SWM_GRID"
class StageFactorDefinitionMethod(Enum):
	ABSOLUTE_STAGE_FACTOR = 0
	RELATIVE_STAGE_FACTOR = 1
class JointTypes(Enum):
	JOINT_NONE = "JOINT_NONE"
	JOINT_MOHR_COULOMB = "JOINT_MOHR_COULOMB"
	JOINT_BARTON_BANDIS = "JOINT_BARTON_BANDIS"
	JOINT_HYPERBOLIC_SIMPLE = "JOINT_HYPERBOLIC_SIMPLE"
	JOINT_MATERIAL_DEPENDENT = "JOINT_MATERIAL_DEPENDENT"
	JOINT_HYPERBOLIC_SOFTENING = "JOINT_HYPERBOLIC_SOFTENING"
	JOINT_DISPLACEMENT_DEPENDENT = "JOINT_DISPLACEMENT_DEPENDENT"
class AdditionalPressureType(Enum):
	JOINT_ADDITIONAL_PRESSURE_BY_VALUE = "JOINT_ADDITIONAL_PRESSURE_BY_VALUE"
	JOINT_ADDITIONAL_PRESSURE_BY_PIEZO = "JOINT_ADDITIONAL_PRESSURE_BY_PIEZO"
class DefineStiffness(Enum):
	DEFINE_PARAMETER = "DEFINE_PARAMETER"
	MATERIAL_DEPENDENT = "MATERIAL_DEPENDENT"
class PileApplicationType(Enum):
	APPLICATION_CONSTANT = "APPLICATION_CONSTANT"
	APPLICATION_BY_LENGTH = "APPLICATION_BY_LENGTH"
class PileEndCondition(Enum):
	FP_NONE = "FP_NONE"
	FP_FORCE = "FP_FORCE"
	FP_DISPLACEMENT = "FP_DISPLACEMENT"
class PileForceApplicationPoint(Enum):
	FP_TOP = "FP_TOP"
	FP_BOTTOM = "FP_BOTTOM"
class PileSkinResistanceType(Enum):
	SKIN_RESISTANCE_ELASTIC = "SKIN_RESISTANCE_ELASTIC"
	SKIN_RESISTANCE_C_PHI = "SKIN_RESISTANCE_C_PHI"
	SKIN_RESISTANCE_LINEAR = "SKIN_RESISTANCE_LINEAR"
	SKIN_RESISTANCE_MULTI_LINEAR = "SKIN_RESISTANCE_MULTI_LINEAR"
	SKIN_RESISTANCE_MATERIAL_DEPENDENT = "SKIN_RESISTANCE_MATERIAL_DEPENDENT"
class PileDefinitionMethod(Enum):
	DISTANCE_FROM_TOP = "DISTANCE_FROM_TOP"
	ELEVATION = "ELEVATION"
class PileConnectionType(Enum):
	CONNECT_FREE = "CONNECT_FREE"
	CONNECT_HINGED = "CONNECT_HINGED"
	CONNECT_RIGID = "CONNECT_RIGID"
	CONNECT_SEMIRIGID = "CONNECT_SEMIRIGID"
class CompositeJointPlacementTypes(Enum):
	BETWEEN_SOIL_ROCK_AND_FIRST_LINER = "BETWEEN_SOIL_ROCK_AND_FIRST_LINER"
	BETWEEN_FIRST_AND_SECOND_LINER = "BETWEEN_FIRST_AND_SECOND_LINER"
	BETWEEN_SECOND_AND_THIRD_LINER = "BETWEEN_SECOND_AND_THIRD_LINER"
	BETWEEN_THIRD_AND_FOURTH_LINER = "BETWEEN_THIRD_AND_FOURTH_LINER"
class ThermalType(Enum):
	THERMAL_CONSTANT = "THERMAL_CONSTANT"
	THERMAL_JOHANSEN = "THERMAL_JOHANSEN"
	THERMAL_JOHANSEN_LU = "THERMAL_JOHANSEN_LU"
	THERMAL_DEVRIES = "THERMAL_DEVRIES"
	THERMAL_COTE_AND_KONRAD = "THERMAL_COTE_AND_KONRAD"
	THERMAL_TABULAR = "THERMAL_TABULAR"
class ThermalWaterContentMethodType(Enum):
	THERMAL_WATER_CONTENT_FROM_GROUNDWATER = "THERMAL_WATER_CONTENT_FROM_GROUNDWATER"
	THERMAL_WATER_CONTENT_DEFINE = "THERMAL_WATER_CONTENT_DEFINE"
class ThermalHeatCapacityType(Enum):
	THERMAL_HEAT_CAPACITY_CONSTANT = "THERMAL_HEAT_CAPACITY_CONSTANT"
	THERMAL_HEAT_CAPACITY_JAMENEWMAN = "THERMAL_HEAT_CAPACITY_JAMENEWMAN"
	THERMAL_HEAT_CAPACITY_CUSTOM = "THERMAL_HEAT_CAPACITY_CUSTOM"
class ThermalWaterContentType(Enum):
	THERMAL_WATER_CONTENT_KONRAD = "THERMAL_WATER_CONTENT_KONRAD"
	THERMAL_WATER_CONTENT_TICE_ANDERSON = "THERMAL_WATER_CONTENT_TICE_ANDERSON"
	THERMAL_WATER_CONTENT_HYDRO_MODEL = "THERMAL_WATER_CONTENT_HYDRO_MODEL"
	THERMAL_WATER_CONTENT_CUSTOM = "THERMAL_WATER_CONTENT_CUSTOM"
	THERMAL_WATER_CONTENT_DEFAULT = "THERMAL_WATER_CONTENT_DEFAULT"
class ThermalVolumetricDepencenceType(Enum):
	THERMAL_VOLUMETRIC_DEPENDENCE_TEMPERATURE = "THERMAL_VOLUMETRIC_DEPENDENCE_TEMPERATURE"
	THERMAL_VOLUMETRIC_DEPENDENCE_WATER_CONTENT = "THERMAL_VOLUMETRIC_DEPENDENCE_WATER_CONTENT"
class GroundWaterModes(Enum):
	SL_WATER_MODE_SIMPLE = "SL_WATER_MODE_SIMPLE"
	SL_WATER_MODE_FREDLUND = "SL_WATER_MODE_FREDLUND"
	SL_WATER_MODE_VAN_GENUCHTEN = "SL_WATER_MODE_VAN_GENUCHTEN"
	SL_WATER_MODE_BROOK = "SL_WATER_MODE_BROOK"
	SL_WATER_MODE_USER_DEFINED = "SL_WATER_MODE_USER_DEFINED"
	SL_WATER_MODE_GARDNER = "SL_WATER_MODE_GARDNER"
	SL_WATER_MODE_CONSTANT = "SL_WATER_MODE_CONSTANT"
class ThermalSoilType(Enum):
	THERMAL_SOIL_FINE = "THERMAL_SOIL_FINE"
	THERMAL_SOIL_COARSE = "THERMAL_SOIL_COARSE"
	THERMAL_SOIL_CRUSHED_ROCK = "THERMAL_SOIL_CRUSHED_ROCK"
	THERMAL_SOIL_PEAT = "THERMAL_SOIL_PEAT"
class MVModel(Enum):
	MV_NONE = "MV_NONE"
	MV_CONSTANT = "MV_CONSTANT"
	MV_FLUID = "MV_FLUID"
	MV_1D_ELASTIC = "MV_1D_ELASTIC"
	MV_2D_ELASTIC = "MV_2D_ELASTIC"
	MV_COUPLED = "MV_COUPLED"
class WCInputType(Enum):
	WC_INPUT_WC = "WC_INPUT_WC"
	WC_INPUT_DOS = "WC_INPUT_DOS"
class UnsaturatedParameterType(Enum):
	UNSATURATED_NOT_APPLIED = "UNSATURATED_NOT_APPLIED"
	UNSATURATED_SHEAR_STRESS = "UNSATURATED_SHEAR_STRESS"
	UNSATURATED_SINGLE_EFFECTIVE_STRESS = "UNSATURATED_SINGLE_EFFECTIVE_STRESS"
class UnsaturatedShearStrengthType(Enum):
	UNSATURATED_FREDLUND = "UNSATURATED_FREDLUND"
	UNSATURATED_VANAPALLI = "UNSATURATED_VANAPALLI"
class UnsaturatedSingleEffectiveStressMethod(Enum):
	UNSATURATED_BISHOP = "UNSATURATED_BISHOP"
	UNSATURATED_TABULAR_VALUE = "UNSATURATED_TABULAR_VALUE"
	UNSATURATED_GUDEHUS_1995 = "UNSATURATED_GUDEHUS_1995"
	UNSATURATED_KHALILI_2004 = "UNSATURATED_KHALILI_2004"
	UNSATURATED_BOLZON_1996 = "UNSATURATED_BOLZON_1996"
	UNSATURATED_AITCHISON_1960 = "UNSATURATED_AITCHISON_1960"
	UNSATURATED_KOHGO_1993 = "UNSATURATED_KOHGO_1993"
class UnsaturatedTabularValueMethod(Enum):
	UNSATURATED_RESPECT_SUCTION = "UNSATURATED_RESPECT_SUCTION"
	UNSATURATED_RESPECT_DEGREE_SATURATION = "UNSATURATED_RESPECT_DEGREE_SATURATION"
	UNSATURATED_RESPECT_EFFECTIVE_DEGREE_SATURATION = "UNSATURATED_RESPECT_EFFECTIVE_DEGREE_SATURATION"
class InitialElementLoadingType(Enum):
	INITIAL_MAT_LOADING__FIELD_STRESS_ONLY = "INITIAL_MAT_LOADING__FIELD_STRESS_ONLY"
	INITIAL_MAT_LOADING__BOTH_FIELD_AND_BODY = "INITIAL_MAT_LOADING__BOTH_FIELD_AND_BODY"
	INITIAL_MAT_LOADING__BODY_FORCE_ONLY = "INITIAL_MAT_LOADING__BODY_FORCE_ONLY"
	INITIAL_MAT_LOADING__NONE = "INITIAL_MAT_LOADING__NONE"
class MaterialElasticityTypes(Enum):
	ISOTROPIC = "ISOTROPIC"
	TRANSVERSELY_ISOTROPIC = "TRANSVERSELY_ISOTROPIC"
	ORTHOTROPIC = "ORTHOTROPIC"
	NON_LINEAR_HYPERBOLIC = "NON_LINEAR_HYPERBOLIC"
	NON_LINEAR_ISOTROPIC = "NON_LINEAR_ISOTROPIC"
	VISCO_ELASTIC = "VISCO_ELASTIC"
	CUSTOM_STIFFNESS = "CUSTOM_STIFFNESS"
class ElasticParameters(Enum):
	CONSTANT_SHEAR_MODULUS = "CONSTANT_SHEAR_MODULUS"
	CONSTANT_POISSON_RATIO = "CONSTANT_POISSON_RATIO"
class SpecificVolumeAtUnitPressure(Enum):
	CRITICAL_STATE_LINE = "CRITICAL_STATE_LINE"
	NORMAL_COMPRESSION_LINE = "NORMAL_COMPRESSION_LINE"
class InitialStateOfConsolidation(Enum):
	PRECONSOLIDATION_PRESSURE = "PRECONSOLIDATION_PRESSURE"
	OVERCONSOLIDATION_RATIO = "OVERCONSOLIDATION_RATIO"
class TensileCutoffOptions(Enum):
	TENSILE_CUTOFF_NONE = "TENSILE_CUTOFF_NONE"
	TENSILE_CUTOFF_HOEK_MARTIN = "TENSILE_CUTOFF_HOEK_MARTIN"
	TENSILE_CUTOFF_USER_DEFINED = "TENSILE_CUTOFF_USER_DEFINED"
class NLIFormulaTypes(Enum):
	NLI_TYPE_FORMULA1 = "NLI_TYPE_FORMULA1"
	NLI_TYPE_FORMULA2 = "NLI_TYPE_FORMULA2"
	NLI_TYPE_FORMULA3 = "NLI_TYPE_FORMULA3"
	NLI_TYPE_FORMULA4 = "NLI_TYPE_FORMULA4"
class PoissonRatioType(Enum):
	POISSON_RATIO_CONSTANT = "POISSON_RATIO_CONSTANT"
	POISSON_RATIO_STRESS_DEPENDENT = "POISSON_RATIO_STRESS_DEPENDENT"
class AnisotropyDefinitions(Enum):
	ANISOTROPY_DEFINITION_ANGLE = "ANISOTROPY_DEFINITION_ANGLE"
	ANISOTROPY_DEFINITION_SURFACE = "ANISOTROPY_DEFINITION_SURFACE"
class MCCapType(Enum):
	MC_CAP_VERTICAL = "MC_CAP_VERTICAL"
	MC_CAP_ELLIPTICAL = "MC_CAP_ELLIPTICAL"
class CapHardeningTypes(Enum):
	MC_CAP_HARDENING_EXPONENTIAL = "MC_CAP_HARDENING_EXPONENTIAL"
	MC_CAP_HARDENING_TABULAR = "MC_CAP_HARDENING_TABULAR"
class CapTypes(Enum):
	MC_CAP_TYPE_NOT_ACTIVE = "MC_CAP_TYPE_NOT_ACTIVE"
	MC_CAP_TYPE_VERTICAL = "MC_CAP_TYPE_VERTICAL"
	MC_CAP_TYPE_ELLIPTICAL = "MC_CAP_TYPE_ELLIPTICAL"
class ConeHardeningTypes(Enum):
	CONE_HARDENING_EXPONENTIAL = "CONE_HARDENING_EXPONENTIAL"
	CONE_HARDENING_TABULAR = "CONE_HARDENING_TABULAR"
class DilationTypes(Enum):
	DILATION_COMPACTION = "DILATION_COMPACTION"
	DILATION_ANGLE = "DILATION_ANGLE"
class HatchStyle(Enum):
	HatchStyleVertical = "HatchStyleVertical"
	HatchStyleForwardDiagonal = "HatchStyleForwardDiagonal"
	HatchStyleBackwardDiagonal = "HatchStyleBackwardDiagonal"
	HatchStyleCross = "HatchStyleCross"
	HatchStyleDiagonalCross = "HatchStyleDiagonalCross"
	HatchStyle05Percent = "HatchStyle05Percent"
	HatchStyle10Percent = "HatchStyle10Percent"
	HatchStyle20Percent = "HatchStyle20Percent"
	HatchStyle25Percent = "HatchStyle25Percent"
	HatchStyle30Percent = "HatchStyle30Percent"
	HatchStyle40Percent = "HatchStyle40Percent"
	HatchStyle50Percent = "HatchStyle50Percent"
	HatchStyle60Percent = "HatchStyle60Percent"
	HatchStyle70Percent = "HatchStyle70Percent"
	HatchStyle75Percent = "HatchStyle75Percent"
	HatchStyle80Percent = "HatchStyle80Percent"
	HatchStyle90Percent = "HatchStyle90Percent"
	HatchStyleLightDownwardDiagonal = "HatchStyleLightDownwardDiagonal"
	HatchStyleLightUpwardDiagonal = "HatchStyleLightUpwardDiagonal"
	HatchStyleDarkDownwardDiagonal = "HatchStyleDarkDownwardDiagonal"
	HatchStyleDarkUpwardDiagonal = "HatchStyleDarkUpwardDiagonal"
	HatchStyleWideDownwardDiagonal = "HatchStyleWideDownwardDiagonal"
	HatchStyleWideUpwardDiagonal = "HatchStyleWideUpwardDiagonal"
	HatchStyleLightVertical = "HatchStyleLightVertical"
	HatchStyleLightHorizontal = "HatchStyleLightHorizontal"
	HatchStyleNarrowVertical = "HatchStyleNarrowVertical"
	HatchStyleNarrowHorizontal = "HatchStyleNarrowHorizontal"
	HatchStyleDarkVertical = "HatchStyleDarkVertical"
	HatchStyleDarkHorizontal = "HatchStyleDarkHorizontal"
	HatchStyleDashedDownwardDiagonal = "HatchStyleDashedDownwardDiagonal"
	HatchStyleDashedUpwardDiagonal = "HatchStyleDashedUpwardDiagonal"
	HatchStyleDashedHorizontal = "HatchStyleDashedHorizontal"
	HatchStyleDashedVertical = "HatchStyleDashedVertical"
	HatchStyleSmallConfetti = "HatchStyleSmallConfetti"
	HatchStyleLargeConfetti = "HatchStyleLargeConfetti"
	HatchStyleZigZag = "HatchStyleZigZag"
	HatchStyleWave = "HatchStyleWave"
	HatchStyleDiagonalBrick = "HatchStyleDiagonalBrick"
	HatchStyleHorizontalBrick = "HatchStyleHorizontalBrick"
	HatchStyleWeave = "HatchStyleWeave"
	HatchStylePlaid = "HatchStylePlaid"
	HatchStyleDivot = "HatchStyleDivot"
	HatchStyleDottedGrid = "HatchStyleDottedGrid"
	HatchStyleDottedDiamond = "HatchStyleDottedDiamond"
	HatchStyleShingle = "HatchStyleShingle"
	HatchStyleTrellis = "HatchStyleTrellis"
	HatchStyleSphere = "HatchStyleSphere"
	HatchStyleSmallGrid = "HatchStyleSmallGrid"
	HatchStyleSmallCheckerBoard = "HatchStyleSmallCheckerBoard"
	HatchStyleLargeCheckerBoard = "HatchStyleLargeCheckerBoard"
	HatchStyleOutlinedDiamond = "HatchStyleOutlinedDiamond"
class UnloadingConditions(Enum):
	UC_MEAN_STRESS = "UC_MEAN_STRESS"
	UC_DEVIATORIC_STRESS = "UC_DEVIATORIC_STRESS"
	UC_VOLUMETRIC_STRAIN = "UC_VOLUMETRIC_STRAIN"
	UC_DEVIATORIC_STRAIN = "UC_DEVIATORIC_STRAIN"
class CustomMode(Enum):
	CUSTOM_Q = "CUSTOM_Q"
	CUSTOM_P = "CUSTOM_P"
	CUSTOM_S3 = "CUSTOM_S3"
	CUSTOM_U = "CUSTOM_U"
	CUSTOM_EPSV = "CUSTOM_EPSV"
	CUSTOM_GAMMA = "CUSTOM_GAMMA"
class StressHistoryTypes(Enum):
	SHT_OCR = "SHT_OCR"
	SHT_PC = "SHT_PC"
class StressHistoryDefinitionMethods(Enum):
	STRESS_HISTORY_CONSTANT = "STRESS_HISTORY_CONSTANT"
	STRESS_HISTORY_DEPTH = "STRESS_HISTORY_DEPTH"
	STRESS_HISTORY_ELEVATION = "STRESS_HISTORY_ELEVATION"
class MaterialBehaviours(Enum):
	DRAINED = "DRAINED"
	UNDRAINED = "UNDRAINED"
class StrengthCriteriaTypes(Enum):
	MOHR_COULOMB = "MOHR_COULOMB"
	HOEK_BROWN = "HOEK_BROWN"
	DRUCKER_PRAGER = "DRUCKER_PRAGER"
	GENERALIZED_HOEK_BROWN = "GENERALIZED_HOEK_BROWN"
	CAM_CLAY = "CAM_CLAY"
	MODIFIED_CAM_CLAY = "MODIFIED_CAM_CLAY"
	DISCRETE_FUNCTION = "DISCRETE_FUNCTION"
	MOHR_COULOMB_CAP = "MOHR_COULOMB_CAP"
	SOFTENING_HARDENING = "SOFTENING_HARDENING"
	BARTON_BANDIS = "BARTON_BANDIS"
	HYPERBOLIC = "HYPERBOLIC"
	POWER_CURVE = "POWER_CURVE"
	SHEAR_NORMAL_FUNCTION = "SHEAR_NORMAL_FUNCTION"
	BOUNDING_SURFACE_PLASTICITY = "BOUNDING_SURFACE_PLASTICITY"
	MANZARI_AND_DAFALIAS = "MANZARI_AND_DAFALIAS"
	SNOWDEN_MODIFIED_ANISOTROPIC_LINEAR = "SNOWDEN_MODIFIED_ANISOTROPIC_LINEAR"
	ANISOTROPIC_LINEAR = "ANISOTROPIC_LINEAR"
	GENERALIZED_ANISOTROPIC = "GENERALIZED_ANISOTROPIC"
	SHANSEP = "SHANSEP"
	VERTICAL_STRESS_RATIO = "VERTICAL_STRESS_RATIO"
	BARCELONA_BASIC = "BARCELONA_BASIC"
	CHSOIL = "CHSOIL"
	CYSOIL = "CYSOIL"
	DOUBLE_YIELD = "DOUBLE_YIELD"
	HARDENING_SOIL = "HARDENING_SOIL"
	HARDENING_SOIL_SMALL_STRAIN_STIFFNESS = "HARDENING_SOIL_SMALL_STRAIN_STIFFNESS"
	SOFT_SOIL = "SOFT_SOIL"
	SOFT_SOIL_CREEP = "SOFT_SOIL_CREEP"
	SWELLING_ROCK = "SWELLING_ROCK"
	JOINTED_MOHR_COULOMB = "JOINTED_MOHR_COULOMB"
	JOINTED_GENERALIZED_HOEK_BROWN = "JOINTED_GENERALIZED_HOEK_BROWN"
	NORSAND = "NORSAND"
	FINN = "FINN"
	PM4_SAND = "PM4_SAND"
	PM4_SILT = "PM4_SILT"
class HuTypes(Enum):
	HT_CUSTOM = "HT_CUSTOM"
	HT_AUTO = "HT_AUTO"
class EnhancedSimpleSoilTypes(Enum):
	SL_ES_SOIL_TYPE_GENERAL = "SL_ES_SOIL_TYPE_GENERAL"
	SL_ES_SOIL_TYPE_SAND = "SL_ES_SOIL_TYPE_SAND"
	SL_ES_SOIL_TYPE_SILT = "SL_ES_SOIL_TYPE_SILT"
	SL_ES_SOIL_TYPE_CLAY = "SL_ES_SOIL_TYPE_CLAY"
	SL_ES_SOIL_TYPE_LOAM = "SL_ES_SOIL_TYPE_LOAM"
class DilationOption(Enum):
	DILATION_ONLY = "DILATION_ONLY"
	DILATION_ROWES = "DILATION_ROWES"
class CySoilCapOption(Enum):
	CYS_CAP_NON = "CYS_CAP_NON"
	CYS_CAP_ELLIPTICAL = "CYS_CAP_ELLIPTICAL"
class Dilatancy(Enum):
	DILATANCY_DEACTIVATED = "DILATANCY_DEACTIVATED"
	DILATANCY_ACTIVATED = "DILATANCY_ACTIVATED"
class InitialConsolidation(Enum):
	OVER_CONSOLIDATION_RATIO = "OVER_CONSOLIDATION_RATIO"
	CONSOL_INITIAL_MEAN_STRESS = "CONSOL_INITIAL_MEAN_STRESS"
class SwellingForm(Enum):
	WITTKE = "WITTKE"
	ANAGNOSTOU = "ANAGNOSTOU"
class WaterCondition(Enum):
	SWELLING = "SWELLING"
	SWELLING_WITH_WATER = "SWELLING_WITH_WATER"
class ViscoElasticTypes(Enum):
	VET_MAXWELL = "VET_MAXWELL"
	VET_BURGERS = "VET_BURGERS"
	VET_STANDARD = "VET_STANDARD"
class NorSandInitialConsolidationCondition(Enum):
	NORSAND_OCR = "NORSAND_OCR"
	NORSAND_INITIAL_MEAN_STRESS = "NORSAND_INITIAL_MEAN_STRESS"
class FinnFormula(Enum):
	FINN_MARTIN = "FINN_MARTIN"
	FINN_BYRNE = "FINN_BYRNE"
class FinnByrneDefinition(Enum):
	FINN_BYRNE_C1_C2 = "FINN_BYRNE_C1_C2"
	FINN_BYRNE_N1 = "FINN_BYRNE_N1"
class DatumType(Enum):
	DATUM_TYPE_DEPTH = "DATUM_TYPE_DEPTH"
	DATUM_TYPE_RADIAL = "DATUM_TYPE_RADIAL"
class SnowdenAnisotropicFunctionType(Enum):
	FUNCTION_TYPE_SHEAR_NORMAL = "FUNCTION_TYPE_SHEAR_NORMAL"
	FUNCTION_TYPE_COHESION_PHI = "FUNCTION_TYPE_COHESION_PHI"
