import unittest
import os, sys, inspect
import shutil
import parentDirectoryHelper
from rs2.modeler.RS2Modeler import RS2Modeler
from rs2.modeler.properties.PropertyEnums import*

parentDirectoryHelper.addParentDirectoryToPath()

class TestReinforcedConcrete(unittest.TestCase):
    def setUp(self):
        parentDirectory = parentDirectoryHelper.getParentDirectory()
        blankModelPath = f"{parentDirectory}/resources/starterProject.fez"
        self.copiedModelPath = f"{parentDirectory}/resources/testProject.fez"
        shutil.copy(blankModelPath, self.copiedModelPath)
        self.modeler = RS2Modeler()
        self.model = self.modeler.openFile(self.copiedModelPath)
        self.liner = self.model.getAllLinerProperties()[0]
    def tearDown(self):
        self.model.close()
        os.remove(self.copiedModelPath)
    def testReinforcedConcreteProperty(self):
        liner = self.liner
        self.liner.setLinerType(LinerTypes.REINFORCED_CONCRETE)
        liner.ReinforcedConcrete.setConcreteUnitWeight(836.5)
        liner.ReinforcedConcrete.setIncludeWeightInStressAnalysis(0)
        liner.ReinforcedConcrete.setInitialTemperature(972.5)
        liner.ReinforcedConcrete.setReinforcement(1)
        liner.ReinforcedConcrete.setSpacing(762.9)
        liner.ReinforcedConcrete.setSectionDepth(1413.6)
        liner.ReinforcedConcrete.setArea(468.3)
        liner.ReinforcedConcrete.setMomentOfInertia(2350.4)
        liner.ReinforcedConcrete.setYoungsModulus(2598.3)
        liner.ReinforcedConcrete.setCompressiveStrength(2572.7)
        liner.ReinforcedConcrete.setTensileStrength(2605.0)
        liner.ReinforcedConcrete.setWeight(3213.4)
        liner.ReinforcedConcrete.setConcrete(1)
        liner.ReinforcedConcrete.setThickness(176.8)
        liner.ReinforcedConcrete.setConcreteYoungsModulus(1508.0)
        liner.ReinforcedConcrete.setPoissonRatio(857.2)
        liner.ReinforcedConcrete.setConcreteCompressiveStrength(3215.6)
        liner.ReinforcedConcrete.setConcreteTensileStrength(1475.5)
        liner.ReinforcedConcrete.setMaterialType(MaterialType.PLASTIC)
        liner.ReinforcedConcrete.setSlidingGap(0)
        liner.ReinforcedConcrete.setStrainAtLocking(3008.6)
        liner.ReinforcedConcrete.setBeamElementFormulation(LinerFormulation.TIMOSHENKO)
        liner.ReinforcedConcrete.setAxialStrainExpansion(2917.7)
        liner.ReinforcedConcrete.setActivateThermal(1)
        liner.ReinforcedConcrete.setStaticTemperatureMode(StaticWaterModes.GRID)
        liner.ReinforcedConcrete.setStaticTemperature(1374.4)
        liner.ReinforcedConcrete.setConductivity(1257.7)
        liner.ReinforcedConcrete.setSpecificHeatCapacity(1702.5)
        liner.ReinforcedConcrete.setThermalExpansion(0)
        liner.ReinforcedConcrete.setExpansionCoefficient(2489.6)
        liner.ReinforcedConcrete.setStageConcreteProperties(0)
        liner.ReinforcedConcrete.setStaticTemperatureGridToUse("None")
        self.model.save()
        self.model.close()
        self.model = self.modeler.openFile(self.copiedModelPath)
        self.liner = self.model.getAllLinerProperties()[0]
        liner = self.liner
        self.assertEqual(liner.ReinforcedConcrete.getConcreteUnitWeight(), 836.5)
        self.assertEqual(liner.ReinforcedConcrete.getIncludeWeightInStressAnalysis(), 0)
        self.assertEqual(liner.ReinforcedConcrete.getInitialTemperature(), 972.5)
        self.assertEqual(liner.ReinforcedConcrete.getReinforcement(), 1)
        self.assertEqual(liner.ReinforcedConcrete.getSpacing(), 762.9)
        self.assertEqual(liner.ReinforcedConcrete.getSectionDepth(), 1413.6)
        self.assertEqual(liner.ReinforcedConcrete.getArea(), 468.3)
        self.assertEqual(liner.ReinforcedConcrete.getMomentOfInertia(), 2350.4)
        self.assertEqual(liner.ReinforcedConcrete.getYoungsModulus(), 2598.3)
        self.assertEqual(liner.ReinforcedConcrete.getCompressiveStrength(), 2572.7)
        self.assertEqual(liner.ReinforcedConcrete.getTensileStrength(), 2605.0)
        self.assertEqual(liner.ReinforcedConcrete.getWeight(), 3213.4)
        self.assertEqual(liner.ReinforcedConcrete.getConcrete(), 1)
        self.assertEqual(liner.ReinforcedConcrete.getThickness(), 176.8)
        self.assertEqual(liner.ReinforcedConcrete.getConcreteYoungsModulus(), 1508.0)
        self.assertEqual(liner.ReinforcedConcrete.getPoissonRatio(), 857.2)
        self.assertEqual(liner.ReinforcedConcrete.getConcreteCompressiveStrength(), 3215.6)
        self.assertEqual(liner.ReinforcedConcrete.getConcreteTensileStrength(), 1475.5)
        self.assertEqual(liner.ReinforcedConcrete.getMaterialType(), MaterialType.PLASTIC)
        self.assertEqual(liner.ReinforcedConcrete.getSlidingGap(), 0)
        self.assertEqual(liner.ReinforcedConcrete.getStrainAtLocking(), 3008.6)
        self.assertEqual(liner.ReinforcedConcrete.getBeamElementFormulation(), LinerFormulation.TIMOSHENKO)
        self.assertEqual(liner.ReinforcedConcrete.getAxialStrainExpansion(), 2917.7)
        self.assertEqual(liner.ReinforcedConcrete.getActivateThermal(), 1)
        self.assertEqual(liner.ReinforcedConcrete.getStaticTemperatureMode(), StaticWaterModes.GRID)
        self.assertEqual(liner.ReinforcedConcrete.getStaticTemperature(), 1374.4)
        self.assertEqual(liner.ReinforcedConcrete.getConductivity(), 1257.7)
        self.assertEqual(liner.ReinforcedConcrete.getSpecificHeatCapacity(), 1702.5)
        self.assertEqual(liner.ReinforcedConcrete.getThermalExpansion(), 0)
        self.assertEqual(liner.ReinforcedConcrete.getExpansionCoefficient(), 2489.6)
        self.assertEqual(liner.ReinforcedConcrete.getStageConcreteProperties(), 0)
        self.assertEqual(liner.ReinforcedConcrete.getStaticTemperatureGridToUse(), "None")
    def testReinforcedConcreteStageFactors(self):
        self.liner.setLinerType(LinerTypes.REINFORCED_CONCRETE)
        stageFactor = self.liner.ReinforcedConcrete.stageFactorInterface.getDefinedStageFactors()[1]
        stageFactor.setConcreteUnitWeightFactor(2188.4)
        stageFactor.setAreaFactor(812.6)
        stageFactor.setWeightFactor(208.8)
        stageFactor.setThicknessFactor(2180.6)
        stageFactor.setConcreteYoungsModulusFactor(84.0)
        stageFactor.setConcreteCompressiveStrengthFactor(870.1)
        stageFactor.setConcreteTensileStrengthFactor(223.6)
        stageFactor.setAxialStrainExpansionFactor(453.6)
        stageFactor.setConductivityFactor(3206.5)
        stageFactor.setSpecificHeatCapacityFactor(2129.1)
        stageFactor.setExpansionCoefficientFactor(1593.2)
        self.model.save()
        self.model.close()
        self.model = self.modeler.openFile(self.copiedModelPath)
        self.liner = self.model.getAllLinerProperties()[0]
        stageFactor = self.liner.ReinforcedConcrete.stageFactorInterface.getDefinedStageFactors()[1]
        self.assertEqual(stageFactor.getConcreteUnitWeightFactor(), 2188.4)
        self.assertEqual(stageFactor.getAreaFactor(), 812.6)
        self.assertEqual(stageFactor.getWeightFactor(), 208.8)
        self.assertEqual(stageFactor.getThicknessFactor(), 2180.6)
        self.assertEqual(stageFactor.getConcreteYoungsModulusFactor(), 84.0)
        self.assertEqual(stageFactor.getConcreteCompressiveStrengthFactor(), 870.1)
        self.assertEqual(stageFactor.getConcreteTensileStrengthFactor(), 223.6)
        self.assertEqual(stageFactor.getAxialStrainExpansionFactor(), 453.6)
        self.assertEqual(stageFactor.getConductivityFactor(), 3206.5)
        self.assertEqual(stageFactor.getSpecificHeatCapacityFactor(), 2129.1)
        self.assertEqual(stageFactor.getExpansionCoefficientFactor(), 1593.2)
