from rs2.modeler.RS2Modeler import RS2Modeler
from rs2.modeler.properties.PropertyEnums import *
from rs2.modeler.properties.bolt import Tieback

modeler = RS2Modeler()

model = modeler.openFile(r"C:\scriptingModels\tieback_final.fez")

boltList = model.getAllBoltProperties()
bolt1 = boltList[0]
bolt2 = boltList[1]
bolt3 = boltList[2]
bolt4 = boltList[3]
bolt5 = boltList[4]
bolt6 = boltList[5]
bolt7 = boltList[6]
bolt8 = boltList[7]
bolt9 = boltList[8]
bolt10 = boltList[9]
bolt11 = boltList[10]
bolt12 = boltList[11]
bolt13 = boltList[12]
bolt14 = boltList[13]
bolt15 = boltList[14]
bolt16 = boltList[15]

bolt1.setBoltType(BoltTypes.TIEBACK_BOLT)
bolt1.Tieback.setBoltDiameter(1.1)
bolt1.Tieback.setBoltModulusE(1.2)
bolt1.Tieback.setBoltModel(BoltModels.P2_BOLT_PLASTIC)
bolt1.Tieback.setTensileCapacity(1.43)
bolt1.Tieback.setResidualTensileCapacity(1.4)
bolt1.Tieback.setOutofPlaneSpacing(1.5)
bolt1.Tieback.setMaterialDependent(True)
bolt1.Tieback.setBondStrengthCoefficient(1.6)
bolt1.Tieback.setBondShearStiffnessCoefficient(1.7)
bolt1.Tieback.setJointShear(True)
bolt1.Tieback.setBoreholeDiameter(1.8)
bolt1.Tieback.setPreTensioningForce(1.9)
bolt1.Tieback.setConstantPretensioningForceInInstallStage(True)
bolt1.Tieback.setFacePlates(True)
bolt1.Tieback.setAddPullOutForce(True)
bolt1.Tieback.setPullOutForce(1.11)
bolt1.Tieback.setUseBondPercentageLength(True)
bolt1.Tieback.setPercentageBondLength(1)
bolt1.Tieback.setUseSecondaryBondLength(True)
bolt1.Tieback.setSecondaryBondLengthType(SecondaryBondLengthType.P2_BOLT_TIEBACK_SECONDARY_PERCENT)
bolt1.Tieback.setPercentOfSecondaryBondLength(2)
bolt1.Tieback.setDelayInstallAfterBolt(3)

bolt2.setBoltType(BoltTypes.TIEBACK_BOLT)
bolt2.Tieback.setMaterialDependent(False)
bolt2.Tieback.setBondShearStiffness(1.1)
bolt2.Tieback.setBondStrength(1.2)
bolt2.Tieback.setJointShear(False)
bolt2.Tieback.setConstantPretensioningForceInInstallStage(False)
bolt2.Tieback.setFacePlates(False)
bolt2.Tieback.setAddPullOutForce(False)
bolt2.Tieback.setUseBondPercentageLength(False)
bolt2.Tieback.setBondLength(1.3)
bolt2.Tieback.setUseSecondaryBondLength(False)

bolt3.setBoltType(BoltTypes.TIEBACK_BOLT)
bolt3.Tieback.setMaterialDependent(True)
bolt3.Tieback.setBondStrengthCoefficient(1.1)
bolt3.Tieback.setBondShearStiffnessCoefficient(1.2)
bolt3.Tieback.setJointShear(False)
bolt3.Tieback.setConstantPretensioningForceInInstallStage(False)
bolt3.Tieback.setFacePlates(False)
bolt3.Tieback.setAddPullOutForce(False)
bolt3.Tieback.setUseBondPercentageLength(False)
bolt3.Tieback.setUseSecondaryBondLength(False)

bolt4.setBoltType(BoltTypes.TIEBACK_BOLT)
bolt4.Tieback.setMaterialDependent(False)
bolt4.Tieback.setJointShear(True)
bolt4.Tieback.setBoreholeDiameter(19.1)
bolt4.Tieback.setConstantPretensioningForceInInstallStage(False)
bolt4.Tieback.setFacePlates(False)
bolt4.Tieback.setAddPullOutForce(False)
bolt4.Tieback.setUseBondPercentageLength(False)
bolt4.Tieback.setUseSecondaryBondLength(False)

bolt5.setBoltType(BoltTypes.TIEBACK_BOLT)
bolt5.Tieback.setMaterialDependent(False)
bolt5.Tieback.setJointShear(False)
bolt5.Tieback.setConstantPretensioningForceInInstallStage(True)
bolt5.Tieback.setFacePlates(False)
bolt5.Tieback.setAddPullOutForce(False)
bolt5.Tieback.setUseBondPercentageLength(False)
bolt5.Tieback.setUseSecondaryBondLength(False)

bolt6.setBoltType(BoltTypes.TIEBACK_BOLT)
bolt6.Tieback.setMaterialDependent(False)
bolt6.Tieback.setJointShear(False)
bolt6.Tieback.setConstantPretensioningForceInInstallStage(False)
bolt6.Tieback.setFacePlates(True)
bolt6.Tieback.setAddPullOutForce(False)
bolt6.Tieback.setUseBondPercentageLength(False)
bolt6.Tieback.setUseSecondaryBondLength(False)

bolt7.setBoltType(BoltTypes.TIEBACK_BOLT)
bolt7.Tieback.setMaterialDependent(False)
bolt7.Tieback.setJointShear(False)
bolt7.Tieback.setConstantPretensioningForceInInstallStage(False)
bolt7.Tieback.setFacePlates(False)
bolt7.Tieback.setAddPullOutForce(True)
bolt7.Tieback.setPullOutForce(1.1)
bolt7.Tieback.setUseBondPercentageLength(False)
bolt7.Tieback.setUseSecondaryBondLength(False)

bolt8.setBoltType(BoltTypes.TIEBACK_BOLT)
bolt8.Tieback.setMaterialDependent(False)
bolt8.Tieback.setJointShear(False)
bolt8.Tieback.setConstantPretensioningForceInInstallStage(False)
bolt8.Tieback.setFacePlates(False)
bolt8.Tieback.setAddPullOutForce(False)
bolt8.Tieback.setUseBondPercentageLength(True)
bolt8.Tieback.setPercentageBondLength(1)
bolt8.Tieback.setUseSecondaryBondLength(False)

bolt9.setBoltType(BoltTypes.TIEBACK_BOLT)
bolt9.Tieback.setMaterialDependent(False)
bolt9.Tieback.setJointShear(False)
bolt9.Tieback.setConstantPretensioningForceInInstallStage(False)
bolt9.Tieback.setFacePlates(False)
bolt9.Tieback.setAddPullOutForce(False)
bolt9.Tieback.setUseBondPercentageLength(False)
bolt9.Tieback.setUseSecondaryBondLength(True)
bolt9.Tieback.setSecondaryBondLengthType(SecondaryBondLengthType.P2_BOLT_TIEBACK_SECONDARY_PERCENT)
bolt9.Tieback.setPercentOfSecondaryBondLength(1)
bolt9.Tieback.setDelayInstallAfterBolt(2)

bolt10.setBoltType(BoltTypes.TIEBACK_BOLT)
bolt10.Tieback.setMaterialDependent(False)
bolt10.Tieback.setJointShear(False)
bolt10.Tieback.setConstantPretensioningForceInInstallStage(False)
bolt10.Tieback.setFacePlates(False)
bolt10.Tieback.setAddPullOutForce(False)
bolt10.Tieback.setUseBondPercentageLength(False)
bolt10.Tieback.setUseSecondaryBondLength(True)
bolt10.Tieback.setSecondaryBondLengthType(SecondaryBondLengthType.P2_BOLT_TIEBACK_SECONDARY_PHYSICAL)
bolt10.Tieback.setSecondaryBondLength(1)
bolt10.Tieback.setDelayInstallAfterBolt(2)

bolt11.setBoltType(BoltTypes.TIEBACK_BOLT)
bolt11.Tieback.setMaterialDependent(False)
bolt11.Tieback.setJointShear(False)
bolt11.Tieback.setConstantPretensioningForceInInstallStage(False)
bolt11.Tieback.setFacePlates(False)
bolt11.Tieback.setAddPullOutForce(False)
bolt11.Tieback.setUseBondPercentageLength(False)
bolt11.Tieback.setUseSecondaryBondLength(True)
bolt11.Tieback.setSecondaryBondLengthType(SecondaryBondLengthType.P2_BOLT_TIEBACK_SECONDARY_FULLY)
bolt11.Tieback.setDelayInstallAfterBolt(1)

bolt12.setBoltType(BoltTypes.TIEBACK_BOLT)
bolt12.Tieback.setMaterialDependent(True)
bolt12.Tieback.setBondStrengthCoefficient(1.1)
bolt12.Tieback.setBondShearStiffnessCoefficient(1.2)
bolt12.Tieback.setJointShear(False)
bolt12.Tieback.setConstantPretensioningForceInInstallStage(True)
bolt12.Tieback.setFacePlates(False)
bolt12.Tieback.setAddPullOutForce(True)
bolt12.Tieback.setPullOutForce(1.3)
bolt12.Tieback.setUseBondPercentageLength(False)
bolt12.Tieback.setUseSecondaryBondLength(True)
bolt12.Tieback.setSecondaryBondLengthType(SecondaryBondLengthType.P2_BOLT_TIEBACK_SECONDARY_PERCENT)
bolt12.Tieback.setPercentOfSecondaryBondLength(1)
bolt12.Tieback.setDelayInstallAfterBolt(2)

bolt13.setBoltType(BoltTypes.TIEBACK_BOLT)
bolt13.Tieback.setMaterialDependent(False)
bolt13.Tieback.setJointShear(True)
bolt13.Tieback.setBoreholeDiameter(19.1)
bolt13.Tieback.setConstantPretensioningForceInInstallStage(False)
bolt13.Tieback.setFacePlates(True)
bolt13.Tieback.setAddPullOutForce(False)
bolt13.Tieback.setUseBondPercentageLength(True)
bolt13.Tieback.setPercentageBondLength(1)
bolt13.Tieback.setUseSecondaryBondLength(False)

bolt14.setBoltType(BoltTypes.TIEBACK_BOLT)
bolt14.Tieback.setMaterialDependent(True)
bolt14.Tieback.setBondStrengthCoefficient(1.1)
bolt14.Tieback.setBondShearStiffnessCoefficient(1.2)
bolt14.Tieback.setJointShear(True)
bolt14.Tieback.setBoreholeDiameter(19.1)
bolt14.Tieback.setConstantPretensioningForceInInstallStage(True)
bolt14.Tieback.setFacePlates(True)
bolt14.Tieback.setAddPullOutForce(False)
bolt14.Tieback.setUseBondPercentageLength(False)
bolt14.Tieback.setUseSecondaryBondLength(False)

bolt15.setBoltType(BoltTypes.TIEBACK_BOLT)
bolt15.Tieback.setMaterialDependent(False)
bolt15.Tieback.setJointShear(False)
bolt15.Tieback.setConstantPretensioningForceInInstallStage(False)
bolt15.Tieback.setFacePlates(False)
bolt15.Tieback.setAddPullOutForce(True)
bolt15.Tieback.setPullOutForce(1.1)
bolt15.Tieback.setUseBondPercentageLength(True)
bolt15.Tieback.setPercentageBondLength(1)
bolt15.Tieback.setUseSecondaryBondLength(True)
bolt15.Tieback.setSecondaryBondLengthType(SecondaryBondLengthType.P2_BOLT_TIEBACK_SECONDARY_PERCENT)
bolt15.Tieback.setPercentOfSecondaryBondLength(2)
bolt15.Tieback.setDelayInstallAfterBolt(3)

bolt16.setBoltType(BoltTypes.TIEBACK_BOLT)
bolt16.Tieback.setMaterialDependent(True)
bolt16.Tieback.setBondStrengthCoefficient(1.1)
bolt16.Tieback.setBondShearStiffnessCoefficient(1.2)
bolt16.Tieback.setJointShear(True)
bolt16.Tieback.setBoreholeDiameter(19.1)
bolt16.Tieback.setConstantPretensioningForceInInstallStage(False)
bolt16.Tieback.setFacePlates(False)
bolt16.Tieback.setAddPullOutForce(True)
bolt16.Tieback.setPullOutForce(1.3)
bolt16.Tieback.setUseBondPercentageLength(True)
bolt16.Tieback.setPercentageBondLength(1)
bolt16.Tieback.setUseSecondaryBondLength(False)

'''
assert(bolt1.Tieback.getBoltDiameter(), 1.1)
assert(bolt1.Tieback.getBoltModulusE(), 1.2)
assert(bolt1.Tieback.getBoltModel(), BoltModels.P2_BOLT_PLASTIC)
assert(bolt1.Tieback.getTensileCapacity(), 1.43) 
assert(bolt1.Tieback.getResidualTensileCapacity(), 1.4)
assert(bolt1.Tieback.getOutofPlaneSpacing(), 1.5)  
assert(bolt1.Tieback.getMaterialDependent(), True)
assert(bolt1.Tieback.getBondStrengthCoefficient(), 1.6)
assert(bolt1.Tieback.getBondShearStiffnessCoefficient(), 1.7)
assert(bolt1.Tieback.getJointShear(), True)
assert(bolt1.Tieback.getBoreholeDiameter(), 1.8)
assert(bolt1.Tieback.getPreTensioningForce(), 1.9)
assert(bolt1.Tieback.getConstantPretensioningForceInInstallStage(), True)
assert(bolt1.Tieback.getFacePlates(), True) 
assert(bolt1.Tieback.getAddPullOutForce(), True)
assert(bolt1.Tieback.getPullOutForce(), 1.11)
assert(bolt1.Tieback.getUseBondPercentageLength(), True)
assert(bolt1.Tieback.getPercentageBondLength(), 1)
assert(bolt1.Tieback.getSecondaryBondLength(), True)
assert(bolt1.Tieback.getSecondaryBondLengthType(), SecondaryBondLengthType.P2_BOLT_TIEBACK_SECONDARY_PERCENT)
assert(bolt1.Tieback.getPercentOfSecondaryBondLength(), 2)
assert(bolt1.Tieback.getDelayInstallAfterBolt(), 3)
'''

model.save()

pass