from rs2.modeler.RS2Modeler import RS2Modeler
from rs2.modeler.properties.PropertyEnums import *
from rs2.modeler.properties.bolt import Tieback

modeler = RS2Modeler()

model = modeler.openFile(r"C:\scriptingModels\tieback_final.fez")

boltList = model.getAllBoltProperties()
bolt1 = boltList[0]
bolt2 = boltList[1]
bolt3 = boltList[2]
bolt4 = boltList[3]
bolt5 = boltList[4]
bolt6 = boltList[5]
bolt7 = boltList[6]
bolt8 = boltList[7]
bolt9 = boltList[8]
bolt10 = boltList[9]
bolt11 = boltList[10]
bolt12 = boltList[11]
bolt13 = boltList[12]
bolt14 = boltList[13]
bolt15 = boltList[14]
bolt16 = boltList[15]
bolt17 = boltList[16]
bolt18 = boltList[17]
bolt19 = boltList[18]
bolt20 = boltList[19]
bolt21 = boltList[20]
bolt22 = boltList[21]
bolt23 = boltList[22]
bolt24 = boltList[23]
bolt25 = boltList[24]
bolt26 = boltList[25]
bolt27 = boltList[26]
bolt28 = boltList[27]
bolt29 = boltList[28]

def test1():
    bolt1.setBoltType(BoltTypes.TIEBACK_BOLT)
    bolt1.Tieback.setBoltDiameter(1.1)
    bolt1.Tieback.setBoltModulusE(1.2)
    bolt1.Tieback.setBoltModel(BoltModels.P2_BOLT_PLASTIC)
    bolt1.Tieback.setTensileCapacity(1.43)
    bolt1.Tieback.setResidualTensileCapacity(1.4)
    bolt1.Tieback.setOutofPlaneSpacing(1.5)
    bolt1.Tieback.setMaterialDependent(True)
    bolt1.Tieback.setBondStrengthCoefficient(1.6)
    bolt1.Tieback.setBondShearStiffnessCoefficient(1.7)
    bolt1.Tieback.setJointShear(True)
    bolt1.Tieback.setBoreholeDiameter(1.8)
    bolt1.Tieback.setPreTensioningForce(1.9)
    bolt1.Tieback.setConstantPretensioningForceInInstallStage(True)
    bolt1.Tieback.setFacePlates(True)
    bolt1.Tieback.setAddPullOutForce(True)
    bolt1.Tieback.setPullOutForce(1.11)
    bolt1.Tieback.setUseBondPercentageLength(True)
    bolt1.Tieback.setPercentageBondLength(1)
    bolt1.Tieback.setUseSecondaryBondLength(True)
    bolt1.Tieback.setSecondaryBondLengthType(SecondaryBondLengthType.P2_BOLT_TIEBACK_SECONDARY_PERCENT)
    bolt1.Tieback.setPercentOfSecondaryBondLength(2)
    bolt1.Tieback.setDelayInstallAfterBolt(3)

    assert(bolt1.Tieback.getBoltDiameter(), 1.1)
    assert(bolt1.Tieback.getBoltModulusE(), 1.2)
    assert(bolt1.Tieback.getBoltModel(), BoltModels.P2_BOLT_PLASTIC)
    assert(bolt1.Tieback.getTensileCapacity(), 1.43) 
    assert(bolt1.Tieback.getResidualTensileCapacity(), 1.4)
    assert(bolt1.Tieback.getOutofPlaneSpacing(), 1.5)  
    assert(bolt1.Tieback.getMaterialDependent(), True)
    assert(bolt1.Tieback.getBondStrengthCoefficient(), 1.6)
    assert(bolt1.Tieback.getBondShearStiffnessCoefficient(), 1.7)
    assert(bolt1.Tieback.getJointShear(), True)
    assert(bolt1.Tieback.getBoreholeDiameter(), 1.8)
    assert(bolt1.Tieback.getPreTensioningForce(), 1.9)
    assert(bolt1.Tieback.getConstantPretensioningForceInInstallStage(), True)
    assert(bolt1.Tieback.getFacePlates(), True) 
    assert(bolt1.Tieback.getAddPullOutForce(), True)
    assert(bolt1.Tieback.getPullOutForce(), 1.11)
    assert(bolt1.Tieback.getUseBondPercentageLength(), True)
    assert(bolt1.Tieback.getPercentageBondLength(), 1)
    assert(bolt1.Tieback.getSecondaryBondLength(), True)
    assert(bolt1.Tieback.getSecondaryBondLengthType(), SecondaryBondLengthType.P2_BOLT_TIEBACK_SECONDARY_PERCENT)
    assert(bolt1.Tieback.getPercentOfSecondaryBondLength(), 2)
    assert(bolt1.Tieback.getDelayInstallAfterBolt(), 3)

def test2():
    bolt2.setBoltType(BoltTypes.TIEBACK_BOLT)
    bolt2.Tieback.setBoltDiameter(1.1)
    bolt2.Tieback.setBoltModulusE(1.2)
    bolt2.Tieback.setBoltModel(BoltModels.P2_BOLT_PLASTIC)
    bolt2.Tieback.setTensileCapacity(1.43)
    bolt2.Tieback.setResidualTensileCapacity(1.4)
    bolt2.Tieback.setOutofPlaneSpacing(1.5)
    bolt2.Tieback.setMaterialDependent(False)
    bolt2.Tieback.setBondShearStiffness(1.6)
    bolt2.Tieback.setBondStrength(1.7)
    bolt2.Tieback.setJointShear(False)
    bolt2.Tieback.setPreTensioningForce(1.9)
    bolt2.Tieback.setConstantPretensioningForceInInstallStage(False)
    bolt2.Tieback.setFacePlates(False)
    bolt2.Tieback.setAddPullOutForce(False)
    bolt2.Tieback.setUseBondPercentageLength(False)
    bolt2.Tieback.setBondLength(1)
    bolt2.Tieback.setUseSecondaryBondLength(False)

    assert(bolt2.Tieback.getBoltDiameter(), 1.1)
    assert(bolt2.Tieback.getBoltModulusE(), 1.2)
    assert(bolt2.Tieback.getBoltModel(), BoltModels.P2_BOLT_PLASTIC)
    assert(bolt2.Tieback.getTensileCapacity(), 1.43) 
    assert(bolt2.Tieback.getResidualTensileCapacity(), 1.4)
    assert(bolt2.Tieback.getOutofPlaneSpacing(), 1.5)  
    assert(bolt2.Tieback.getMaterialDependent(), False)
    assert(bolt2.Tieback.getBondShearStiffness(), 1.6)
    assert(bolt2.Tieback.getBondStrength(), 1.7)
    assert(bolt2.Tieback.getJointShear(), False)
    assert(bolt2.Tieback.getPreTensioningForce(), 1.9)
    assert(bolt2.Tieback.getConstantPretensioningForceInInstallStage(), False)
    assert(bolt2.Tieback.getFacePlates(), False) 
    assert(bolt2.Tieback.getAddPullOutForce(), False)
    assert(bolt2.Tieback.getUseBondPercentageLength(), False)
    assert(bolt2.Tieback.getBondLength(), 1)
    assert(bolt2.Tieback.getSecondaryBondLength(), False)

def test3():
    bolt3.setBoltType(BoltTypes.TIEBACK_BOLT)
    bolt3.Tieback.setBoltDiameter(1.1)
    bolt3.Tieback.setBoltModulusE(1.2)
    bolt3.Tieback.setBoltModel(BoltModels.P2_BOLT_PLASTIC)
    bolt3.Tieback.setTensileCapacity(1.43)
    bolt3.Tieback.setResidualTensileCapacity(1.4)
    bolt3.Tieback.setOutofPlaneSpacing(1.5)
    bolt3.Tieback.setMaterialDependent(True)
    bolt3.Tieback.setBondStrengthCoefficient(1.6)
    bolt3.Tieback.setBondShearStiffnessCoefficient(1.7)
    bolt3.Tieback.setJointShear(False)
    bolt3.Tieback.setPreTensioningForce(1.9)
    bolt3.Tieback.setConstantPretensioningForceInInstallStage(False)
    bolt3.Tieback.setFacePlates(False)
    bolt3.Tieback.setAddPullOutForce(False)
    bolt3.Tieback.setUseBondPercentageLength(False)
    bolt3.Tieback.setBondLength(1)
    bolt3.Tieback.setUseSecondaryBondLength(False)

    assert(bolt3.Tieback.getBoltDiameter(), 1.1)
    assert(bolt3.Tieback.getBoltModulusE(), 1.2)
    assert(bolt3.Tieback.getBoltModel(), BoltModels.P2_BOLT_PLASTIC)
    assert(bolt3.Tieback.getTensileCapacity(), 1.43) 
    assert(bolt3.Tieback.getResidualTensileCapacity(), 1.4)
    assert(bolt3.Tieback.getOutofPlaneSpacing(), 1.5)  
    assert(bolt3.Tieback.getMaterialDependent(), True)
    assert(bolt3.Tieback.getBondStrengthCoefficient(), 1.6)
    assert(bolt3.Tieback.getBondShearStiffnessCoefficient(), 1.7)
    assert(bolt3.Tieback.getJointShear(), False)
    assert(bolt3.Tieback.getPreTensioningForce(), 1.9)
    assert(bolt3.Tieback.getConstantPretensioningForceInInstallStage(), False)
    assert(bolt3.Tieback.getFacePlates(), False) 
    assert(bolt3.Tieback.getAddPullOutForce(), False)
    assert(bolt3.Tieback.getUseBondPercentageLength(), False)
    assert(bolt3.Tieback.getBondLength(), 1)
    assert(bolt3.Tieback.getSecondaryBondLength(), False)

def test4():
    bolt4.setBoltType(BoltTypes.TIEBACK_BOLT)
    bolt4.Tieback.setBoltDiameter(1.1)
    bolt4.Tieback.setBoltModulusE(1.2)
    bolt4.Tieback.setBoltModel(BoltModels.P2_BOLT_PLASTIC)
    bolt4.Tieback.setTensileCapacity(1.43)
    bolt4.Tieback.setResidualTensileCapacity(1.4)
    bolt4.Tieback.setOutofPlaneSpacing(1.5)
    bolt4.Tieback.setMaterialDependent(False)
    bolt4.Tieback.setBondShearStiffness(1.6)
    bolt4.Tieback.setBondStrength(1.7)
    bolt4.Tieback.setJointShear(True)
    bolt4.Tieback.setBoreholeDiameter(1.8)
    bolt4.Tieback.setPreTensioningForce(1.9)
    bolt4.Tieback.setConstantPretensioningForceInInstallStage(False)
    bolt4.Tieback.setFacePlates(False)
    bolt4.Tieback.setAddPullOutForce(False)
    bolt4.Tieback.setUseBondPercentageLength(False)
    bolt4.Tieback.setBondLength(1)
    bolt4.Tieback.setUseSecondaryBondLength(False)

    assert(bolt4.Tieback.getBoltDiameter(), 1.1)
    assert(bolt4.Tieback.getBoltModulusE(), 1.2)
    assert(bolt4.Tieback.getBoltModel(), BoltModels.P2_BOLT_PLASTIC)
    assert(bolt4.Tieback.getTensileCapacity(), 1.43) 
    assert(bolt4.Tieback.getResidualTensileCapacity(), 1.4)
    assert(bolt4.Tieback.getOutofPlaneSpacing(), 1.5)  
    assert(bolt4.Tieback.getMaterialDependent(), False)
    assert(bolt4.Tieback.getBondShearStiffness(), 1.6)
    assert(bolt4.Tieback.getBondStrength(), 1.7)
    assert(bolt4.Tieback.getJointShear(), True)
    assert(bolt1.Tieback.getBoreholeDiameter(), 1.8)
    assert(bolt4.Tieback.getPreTensioningForce(), 1.9)
    assert(bolt4.Tieback.getConstantPretensioningForceInInstallStage(), False)
    assert(bolt4.Tieback.getFacePlates(), False) 
    assert(bolt4.Tieback.getAddPullOutForce(), False)
    assert(bolt4.Tieback.getUseBondPercentageLength(), False)
    assert(bolt4.Tieback.getBondLength(), 1)
    assert(bolt4.Tieback.getSecondaryBondLength(), False)

def test5():
    bolt5.setBoltType(BoltTypes.TIEBACK_BOLT)
    bolt5.Tieback.setBoltDiameter(1.1)
    bolt5.Tieback.setBoltModulusE(1.2)
    bolt5.Tieback.setBoltModel(BoltModels.P2_BOLT_PLASTIC)
    bolt5.Tieback.setTensileCapacity(1.43)
    bolt5.Tieback.setResidualTensileCapacity(1.4)
    bolt5.Tieback.setOutofPlaneSpacing(1.5)
    bolt5.Tieback.setMaterialDependent(False)
    bolt5.Tieback.setBondShearStiffness(1.6)
    bolt5.Tieback.setBondStrength(1.7)
    bolt5.Tieback.setJointShear(False)
    bolt5.Tieback.setPreTensioningForce(1.9)
    bolt5.Tieback.setConstantPretensioningForceInInstallStage(True)
    bolt5.Tieback.setFacePlates(False)
    bolt5.Tieback.setAddPullOutForce(False)
    bolt5.Tieback.setUseBondPercentageLength(False)
    bolt5.Tieback.setBondLength(1)
    bolt5.Tieback.setUseSecondaryBondLength(False)

    assert(bolt5.Tieback.getBoltDiameter(), 1.1)
    assert(bolt5.Tieback.getBoltModulusE(), 1.2)
    assert(bolt5.Tieback.getBoltModel(), BoltModels.P2_BOLT_PLASTIC)
    assert(bolt5.Tieback.getTensileCapacity(), 1.43) 
    assert(bolt5.Tieback.getResidualTensileCapacity(), 1.4)
    assert(bolt5.Tieback.getOutofPlaneSpacing(), 1.5)  
    assert(bolt5.Tieback.getMaterialDependent(), False)
    assert(bolt5.Tieback.getBondShearStiffness(), 1.6)
    assert(bolt5.Tieback.getBondStrength(), 1.7)
    assert(bolt5.Tieback.getJointShear(), False)
    assert(bolt5.Tieback.getPreTensioningForce(), 1.9)
    assert(bolt5.Tieback.getConstantPretensioningForceInInstallStage(), True)
    assert(bolt5.Tieback.getFacePlates(), False) 
    assert(bolt5.Tieback.getAddPullOutForce(), False)
    assert(bolt5.Tieback.getUseBondPercentageLength(), False)
    assert(bolt5.Tieback.getBondLength(), 1)
    assert(bolt5.Tieback.getSecondaryBondLength(), False)

def test6():
    bolt6.setBoltType(BoltTypes.TIEBACK_BOLT)
    bolt6.Tieback.setBoltDiameter(1.1)
    bolt6.Tieback.setBoltModulusE(1.2)
    bolt6.Tieback.setBoltModel(BoltModels.P2_BOLT_PLASTIC)
    bolt6.Tieback.setTensileCapacity(1.43)
    bolt6.Tieback.setResidualTensileCapacity(1.4)
    bolt6.Tieback.setOutofPlaneSpacing(1.5)
    bolt6.Tieback.setMaterialDependent(False)
    bolt6.Tieback.setBondShearStiffness(1.6)
    bolt6.Tieback.setBondStrength(1.7)
    bolt6.Tieback.setJointShear(False)
    bolt6.Tieback.setPreTensioningForce(1.9)
    bolt6.Tieback.setConstantPretensioningForceInInstallStage(False)
    bolt6.Tieback.setFacePlates(True)
    bolt6.Tieback.setAddPullOutForce(False)
    bolt6.Tieback.setUseBondPercentageLength(False)
    bolt6.Tieback.setBondLength(1)
    bolt6.Tieback.setUseSecondaryBondLength(False)

    assert(bolt6.Tieback.getBoltDiameter(), 1.1)
    assert(bolt6.Tieback.getBoltModulusE(), 1.2)
    assert(bolt6.Tieback.getBoltModel(), BoltModels.P2_BOLT_PLASTIC)
    assert(bolt6.Tieback.getTensileCapacity(), 1.43) 
    assert(bolt6.Tieback.getResidualTensileCapacity(), 1.4)
    assert(bolt6.Tieback.getOutofPlaneSpacing(), 1.5)  
    assert(bolt6.Tieback.getMaterialDependent(), False)
    assert(bolt6.Tieback.getBondShearStiffness(), 1.6)
    assert(bolt6.Tieback.getBondStrength(), 1.7)
    assert(bolt6.Tieback.getJointShear(), False)
    assert(bolt6.Tieback.getPreTensioningForce(), 1.9)
    assert(bolt6.Tieback.getConstantPretensioningForceInInstallStage(), False)
    assert(bolt6.Tieback.getFacePlates(), True) 
    assert(bolt6.Tieback.getAddPullOutForce(), False)
    assert(bolt6.Tieback.getUseBondPercentageLength(), False)
    assert(bolt6.Tieback.getBondLength(), 1)
    assert(bolt6.Tieback.getSecondaryBondLength(), False)

def test7():
    bolt7.setBoltType(BoltTypes.TIEBACK_BOLT)
    bolt7.Tieback.setBoltDiameter(1.1)
    bolt7.Tieback.setBoltModulusE(1.2)
    bolt7.Tieback.setBoltModel(BoltModels.P2_BOLT_PLASTIC)
    bolt7.Tieback.setTensileCapacity(1.43)
    bolt7.Tieback.setResidualTensileCapacity(1.4)
    bolt7.Tieback.setOutofPlaneSpacing(1.5)
    bolt7.Tieback.setMaterialDependent(False)
    bolt7.Tieback.setBondShearStiffness(1.6)
    bolt7.Tieback.setBondStrength(1.7)
    bolt7.Tieback.setJointShear(False)
    bolt7.Tieback.setPreTensioningForce(1.9)
    bolt7.Tieback.setConstantPretensioningForceInInstallStage(False)
    bolt7.Tieback.setFacePlates(False)
    bolt7.Tieback.setAddPullOutForce(True)
    bolt7.Tieback.setPullOutForce(1.11)
    bolt7.Tieback.setUseBondPercentageLength(False)
    bolt7.Tieback.setBondLength(1)
    bolt7.Tieback.setUseSecondaryBondLength(False)

    assert(bolt7.Tieback.getBoltDiameter(), 1.1)
    assert(bolt7.Tieback.getBoltModulusE(), 1.2)
    assert(bolt7.Tieback.getBoltModel(), BoltModels.P2_BOLT_PLASTIC)
    assert(bolt7.Tieback.getTensileCapacity(), 1.43) 
    assert(bolt7.Tieback.getResidualTensileCapacity(), 1.4)
    assert(bolt7.Tieback.getOutofPlaneSpacing(), 1.5)  
    assert(bolt7.Tieback.getMaterialDependent(), False)
    assert(bolt7.Tieback.getBondShearStiffness(), 1.6)
    assert(bolt7.Tieback.getBondStrength(), 1.7)
    assert(bolt7.Tieback.getJointShear(), False)
    assert(bolt7.Tieback.getPreTensioningForce(), 1.9)
    assert(bolt7.Tieback.getConstantPretensioningForceInInstallStage(), False)
    assert(bolt7.Tieback.getFacePlates(), False) 
    assert(bolt7.Tieback.getAddPullOutForce(), True)
    assert(bolt7.Tieback.getPullOutForce(),1.11)
    assert(bolt7.Tieback.getUseBondPercentageLength(), False)
    assert(bolt7.Tieback.getBondLength(), 1)
    assert(bolt7.Tieback.getSecondaryBondLength(), False)

def test8():
    bolt8.setBoltType(BoltTypes.TIEBACK_BOLT)
    bolt8.Tieback.setBoltDiameter(1.1)
    bolt8.Tieback.setBoltModulusE(1.2)
    bolt8.Tieback.setBoltModel(BoltModels.P2_BOLT_PLASTIC)
    bolt8.Tieback.setTensileCapacity(1.43)
    bolt8.Tieback.setResidualTensileCapacity(1.4)
    bolt8.Tieback.setOutofPlaneSpacing(1.5)
    bolt8.Tieback.setMaterialDependent(False)
    bolt8.Tieback.setBondShearStiffness(1.6)
    bolt8.Tieback.setBondStrength(1.7)
    bolt8.Tieback.setJointShear(False)
    bolt8.Tieback.setPreTensioningForce(1.9)
    bolt8.Tieback.setConstantPretensioningForceInInstallStage(False)
    bolt8.Tieback.setFacePlates(False)
    bolt8.Tieback.setAddPullOutForce(False)
    bolt8.Tieback.setUseBondPercentageLength(True)
    bolt8.Tieback.setUseBondPercentageLength(1)
    bolt8.Tieback.setUseSecondaryBondLength(False)

    assert(bolt8.Tieback.getBoltDiameter(), 1.1)
    assert(bolt8.Tieback.getBoltModulusE(), 1.2)
    assert(bolt8.Tieback.getBoltModel(), BoltModels.P2_BOLT_PLASTIC)
    assert(bolt8.Tieback.getTensileCapacity(), 1.43) 
    assert(bolt8.Tieback.getResidualTensileCapacity(), 1.4)
    assert(bolt8.Tieback.getOutofPlaneSpacing(), 1.5)  
    assert(bolt8.Tieback.getMaterialDependent(), False)
    assert(bolt8.Tieback.getBondShearStiffness(), 1.6)
    assert(bolt8.Tieback.getBondStrength(), 1.7)
    assert(bolt8.Tieback.getJointShear(), False)
    assert(bolt8.Tieback.getPreTensioningForce(), 1.9)
    assert(bolt8.Tieback.getConstantPretensioningForceInInstallStage(), False)
    assert(bolt8.Tieback.getFacePlates(), False) 
    assert(bolt8.Tieback.getAddPullOutForce(), False)
    assert(bolt8.Tieback.getUseBondPercentageLength(), True)
    assert(bolt8.Tieback.getUseBondPercentageLength(), 1)
    assert(bolt8.Tieback.getSecondaryBondLength(), False)

def test9():
    bolt9.setBoltType(BoltTypes.TIEBACK_BOLT)
    bolt9.Tieback.setBoltDiameter(1.1)
    bolt9.Tieback.setBoltModulusE(1.2)
    bolt9.Tieback.setBoltModel(BoltModels.P2_BOLT_PLASTIC)
    bolt9.Tieback.setTensileCapacity(1.43)
    bolt9.Tieback.setResidualTensileCapacity(1.4)
    bolt9.Tieback.setOutofPlaneSpacing(1.5)
    bolt9.Tieback.setMaterialDependent(False)
    bolt9.Tieback.setBondShearStiffness(1.6)
    bolt9.Tieback.setBondStrength(1.7)
    bolt9.Tieback.setJointShear(False)
    bolt9.Tieback.setPreTensioningForce(1.9)
    bolt9.Tieback.setConstantPretensioningForceInInstallStage(False)
    bolt9.Tieback.setFacePlates(False)
    bolt9.Tieback.setAddPullOutForce(False)
    bolt9.Tieback.setUseBondPercentageLength(False)
    bolt9.Tieback.setBondLength(1)
    bolt9.Tieback.setUseSecondaryBondLength(True)
    bolt9.Tieback.setSecondaryBondLengthType(SecondaryBondLengthType.P2_BOLT_TIEBACK_SECONDARY_PERCENT)
    bolt9.Tieback.setPercentOfSecondaryBondLength(2)
    bolt9.Tieback.setDelayInstallAfterBolt(3)

    assert(bolt9.Tieback.getBoltDiameter(), 1.1)
    assert(bolt9.Tieback.getBoltModulusE(), 1.2)
    assert(bolt9.Tieback.getBoltModel(), BoltModels.P2_BOLT_PLASTIC)
    assert(bolt9.Tieback.getTensileCapacity(), 1.43) 
    assert(bolt9.Tieback.getResidualTensileCapacity(), 1.4)
    assert(bolt9.Tieback.getOutofPlaneSpacing(), 1.5)  
    assert(bolt9.Tieback.getMaterialDependent(), False)
    assert(bolt9.Tieback.getBondShearStiffness(), 1.6)
    assert(bolt9.Tieback.getBondStrength(), 1.7)
    assert(bolt9.Tieback.getJointShear(), False)
    assert(bolt9.Tieback.getPreTensioningForce(), 1.9)
    assert(bolt9.Tieback.getConstantPretensioningForceInInstallStage(), False)
    assert(bolt9.Tieback.getFacePlates(), False) 
    assert(bolt9.Tieback.getAddPullOutForce(), False)
    assert(bolt9.Tieback.getUseBondPercentageLength(), False)
    assert(bolt9.Tieback.getBondLength(), 1)
    assert(bolt9.Tieback.getSecondaryBondLength(), True)
    assert(bolt9.Tieback.getSecondaryBondLengthType(), SecondaryBondLengthType.P2_BOLT_TIEBACK_SECONDARY_PERCENT)
    assert(bolt9.Tieback.getPercentOfSecondaryBondLength(), 2)
    assert(bolt9.Tieback.getDelayInstallAfterBolt(), 3)

def test10():
    bolt10.setBoltType(BoltTypes.TIEBACK_BOLT)
    bolt10.Tieback.setBoltDiameter(1.1)
    bolt10.Tieback.setBoltModulusE(1.2)
    bolt10.Tieback.setBoltModel(BoltModels.P2_BOLT_PLASTIC)
    bolt10.Tieback.setTensileCapacity(1.43)
    bolt10.Tieback.setResidualTensileCapacity(1.4)
    bolt10.Tieback.setOutofPlaneSpacing(1.5)
    bolt10.Tieback.setMaterialDependent(False)
    bolt10.Tieback.setBondShearStiffness(1.6)
    bolt10.Tieback.setBondStrength(1.7)
    bolt10.Tieback.setJointShear(False)
    bolt10.Tieback.setPreTensioningForce(1.9)
    bolt10.Tieback.setConstantPretensioningForceInInstallStage(False)
    bolt10.Tieback.setFacePlates(False)
    bolt10.Tieback.setAddPullOutForce(False)
    bolt10.Tieback.setUseBondPercentageLength(False)
    bolt10.Tieback.setBondLength(1)
    bolt10.Tieback.setUseSecondaryBondLength(True)
    bolt10.Tieback.setSecondaryBondLengthType(SecondaryBondLengthType.P2_BOLT_TIEBACK_SECONDARY_PHYSICAL)
    bolt10.Tieback.setPercentOfSecondaryBondLength(2)
    bolt10.Tieback.setDelayInstallAfterBolt(3)

    assert(bolt10.Tieback.getBoltDiameter(), 1.1)
    assert(bolt10.Tieback.getBoltModulusE(), 1.2)
    assert(bolt10.Tieback.getBoltModel(), BoltModels.P2_BOLT_PLASTIC)
    assert(bolt10.Tieback.getTensileCapacity(), 1.43) 
    assert(bolt10.Tieback.getResidualTensileCapacity(), 1.4)
    assert(bolt10.Tieback.getOutofPlaneSpacing(), 1.5)  
    assert(bolt10.Tieback.getMaterialDependent(), False)
    assert(bolt10.Tieback.getBondShearStiffness(), 1.6)
    assert(bolt10.Tieback.getBondStrength(), 1.7)
    assert(bolt10.Tieback.getJointShear(), False)
    assert(bolt10.Tieback.getPreTensioningForce(), 1.9)
    assert(bolt10.Tieback.getConstantPretensioningForceInInstallStage(), False)
    assert(bolt10.Tieback.getFacePlates(), False) 
    assert(bolt10.Tieback.getAddPullOutForce(), False)
    assert(bolt10.Tieback.getUseBondPercentageLength(), False)
    assert(bolt10.Tieback.getBondLength(), 1)
    assert(bolt10.Tieback.getSecondaryBondLength(), True)
    assert(bolt10.Tieback.getSecondaryBondLengthType(), SecondaryBondLengthType.P2_BOLT_TIEBACK_SECONDARY_PHYSICAL)
    assert(bolt10.Tieback.getPercentOfSecondaryBondLength(), 2)
    assert(bolt10.Tieback.getDelayInstallAfterBolt(), 3)

def test11():
    bolt11.setBoltType(BoltTypes.TIEBACK_BOLT)
    bolt11.Tieback.setBoltDiameter(1.1)
    bolt11.Tieback.setBoltModulusE(1.2)
    bolt11.Tieback.setBoltModel(BoltModels.P2_BOLT_PLASTIC)
    bolt11.Tieback.setTensileCapacity(1.43)
    bolt11.Tieback.setResidualTensileCapacity(1.4)
    bolt11.Tieback.setOutofPlaneSpacing(1.5)
    bolt11.Tieback.setMaterialDependent(False)
    bolt11.Tieback.setBondShearStiffness(1.6)
    bolt11.Tieback.setBondStrength(1.7)
    bolt11.Tieback.setJointShear(False)
    bolt11.Tieback.setPreTensioningForce(1.9)
    bolt11.Tieback.setConstantPretensioningForceInInstallStage(False)
    bolt11.Tieback.setFacePlates(False)
    bolt11.Tieback.setAddPullOutForce(False)
    bolt11.Tieback.setUseBondPercentageLength(False)
    bolt11.Tieback.setBondLength(1)
    bolt11.Tieback.setUseSecondaryBondLength(True)
    bolt11.Tieback.setSecondaryBondLengthType(SecondaryBondLengthType.P2_BOLT_TIEBACK_SECONDARY_FULLY)
    bolt11.Tieback.setDelayInstallAfterBolt(3)

    assert(bolt11.Tieback.getBoltDiameter(), 1.1)
    assert(bolt11.Tieback.getBoltModulusE(), 1.2)
    assert(bolt11.Tieback.getBoltModel(), BoltModels.P2_BOLT_PLASTIC)
    assert(bolt11.Tieback.getTensileCapacity(), 1.43) 
    assert(bolt11.Tieback.getResidualTensileCapacity(), 1.4)
    assert(bolt11.Tieback.getOutofPlaneSpacing(), 1.5)  
    assert(bolt11.Tieback.getMaterialDependent(), False)
    assert(bolt11.Tieback.getBondShearStiffness(), 1.6)
    assert(bolt11.Tieback.getBondStrength(), 1.7)
    assert(bolt11.Tieback.getJointShear(), False)
    assert(bolt11.Tieback.getPreTensioningForce(), 1.9)
    assert(bolt11.Tieback.getConstantPretensioningForceInInstallStage(), False)
    assert(bolt11.Tieback.getFacePlates(), False) 
    assert(bolt11.Tieback.getAddPullOutForce(), False)
    assert(bolt11.Tieback.getUseBondPercentageLength(), False)
    assert(bolt11.Tieback.getBondLength(), 1)
    assert(bolt11.Tieback.getSecondaryBondLength(), True)
    assert(bolt11.Tieback.getSecondaryBondLengthType(), SecondaryBondLengthType.P2_BOLT_TIEBACK_SECONDARY_FULLY)
    assert(bolt11.Tieback.getDelayInstallAfterBolt(), 3)

def test12():
    bolt12.setBoltType(BoltTypes.TIEBACK_BOLT)
    bolt12.Tieback.setBoltDiameter(1.1)
    bolt12.Tieback.setBoltModulusE(1.2)
    bolt12.Tieback.setBoltModel(BoltModels.P2_BOLT_PLASTIC)
    bolt12.Tieback.setTensileCapacity(1.43)
    bolt12.Tieback.setResidualTensileCapacity(1.4)
    bolt12.Tieback.setOutofPlaneSpacing(1.5)
    bolt12.Tieback.setMaterialDependent(True)
    bolt12.Tieback.setBondStrengthCoefficient(1.6)
    bolt12.Tieback.setBondShearStiffnessCoefficient(1.7)
    bolt12.Tieback.setJointShear(False)
    bolt12.Tieback.setPreTensioningForce(1.9)
    bolt12.Tieback.setConstantPretensioningForceInInstallStage(True)
    bolt12.Tieback.setFacePlates(False)
    bolt12.Tieback.setAddPullOutForce(True)
    bolt12.Tieback.setPullOutForce(1.11)
    bolt12.Tieback.setUseBondPercentageLength(False)
    bolt12.Tieback.setBondLength(1)
    bolt12.Tieback.setUseSecondaryBondLength(True)
    bolt12.Tieback.setSecondaryBondLengthType(SecondaryBondLengthType.P2_BOLT_TIEBACK_SECONDARY_PERCENT)
    bolt12.Tieback.setPercentOfSecondaryBondLength(2)
    bolt12.Tieback.setDelayInstallAfterBolt(3)

    assert(bolt12.Tieback.getBoltDiameter(), 1.1)
    assert(bolt12.Tieback.getBoltModulusE(), 1.2)
    assert(bolt12.Tieback.getBoltModel(), BoltModels.P2_BOLT_PLASTIC)
    assert(bolt12.Tieback.getTensileCapacity(), 1.43) 
    assert(bolt12.Tieback.getResidualTensileCapacity(), 1.4)
    assert(bolt12.Tieback.getOutofPlaneSpacing(), 1.5)  
    assert(bolt12.Tieback.getMaterialDependent(), True)
    assert(bolt12.Tieback.getBondStrengthCoefficient(), 1.6)
    assert(bolt12.Tieback.getBondShearStiffnessCoefficient(), 1.7)
    assert(bolt12.Tieback.getJointShear(), False)
    assert(bolt12.Tieback.getPreTensioningForce(), 1.9)
    assert(bolt12.Tieback.getConstantPretensioningForceInInstallStage(), True)
    assert(bolt12.Tieback.getFacePlates(), False) 
    assert(bolt12.Tieback.getAddPullOutForce(), True)
    assert(bolt12.Tieback.getPullOutForce(), 1.11)
    assert(bolt12.Tieback.getUseBondPercentageLength(), False)
    assert(bolt12.Tieback.getBondLength(), 1)
    assert(bolt12.Tieback.getSecondaryBondLength(), True)
    assert(bolt12.Tieback.getSecondaryBondLengthType(), SecondaryBondLengthType.P2_BOLT_TIEBACK_SECONDARY_PERCENT)
    assert(bolt12.Tieback.getPercentOfSecondaryBondLength(), 2)
    assert(bolt12.Tieback.getDelayInstallAfterBolt(), 3)

def test13():
    bolt13.setBoltType(BoltTypes.TIEBACK_BOLT)
    bolt13.Tieback.setBoltDiameter(1.1)
    bolt13.Tieback.setBoltModulusE(1.2)
    bolt13.Tieback.setBoltModel(BoltModels.P2_BOLT_PLASTIC)
    bolt13.Tieback.setTensileCapacity(1.43)
    bolt13.Tieback.setResidualTensileCapacity(1.4)
    bolt13.Tieback.setOutofPlaneSpacing(1.5)
    bolt13.Tieback.setMaterialDependent(False)
    bolt13.Tieback.setBondShearStiffness(1.6)
    bolt13.Tieback.setBondStrength(1.7)
    bolt13.Tieback.setJointShear(True)
    bolt13.Tieback.setBoreholeDiameter(1.8)
    bolt13.Tieback.setPreTensioningForce(1.9)
    bolt13.Tieback.setConstantPretensioningForceInInstallStage(False)
    bolt13.Tieback.setFacePlates(True)
    bolt13.Tieback.setAddPullOutForce(False)
    bolt13.Tieback.setUseBondPercentageLength(True)
    bolt13.Tieback.setUseBondPercentageLength(1)
    bolt13.Tieback.setUseSecondaryBondLength(False)

    assert(bolt13.Tieback.getBoltDiameter(), 1.1)
    assert(bolt13.Tieback.getBoltModulusE(), 1.2)
    assert(bolt13.Tieback.getBoltModel(), BoltModels.P2_BOLT_PLASTIC)
    assert(bolt13.Tieback.getTensileCapacity(), 1.43) 
    assert(bolt13.Tieback.getResidualTensileCapacity(), 1.4)
    assert(bolt13.Tieback.getOutofPlaneSpacing(), 1.5)  
    assert(bolt13.Tieback.getMaterialDependent(), False)
    assert(bolt13.Tieback.getBondShearStiffness(), 1.6)
    assert(bolt13.Tieback.getBondStrength(), 1.7)
    assert(bolt13.Tieback.getJointShear(), True)
    assert(bolt13.Tieback.getBoreholeDiameter(), 1.8)
    assert(bolt13.Tieback.getPreTensioningForce(), 1.9)
    assert(bolt13.Tieback.getConstantPretensioningForceInInstallStage(), False)
    assert(bolt13.Tieback.getFacePlates(), True) 
    assert(bolt13.Tieback.getAddPullOutForce(), False)
    assert(bolt13.Tieback.getUseBondPercentageLength(), True)
    assert(bolt13.Tieback.getUseBondPercentageLength(), 1)
    assert(bolt13.Tieback.getSecondaryBondLength(), False)

def test14():
    bolt14.setBoltType(BoltTypes.TIEBACK_BOLT)
    bolt14.Tieback.setBoltDiameter(1.1)
    bolt14.Tieback.setBoltModulusE(1.2)
    bolt14.Tieback.setBoltModel(BoltModels.P2_BOLT_PLASTIC)
    bolt14.Tieback.setTensileCapacity(1.43)
    bolt14.Tieback.setResidualTensileCapacity(1.4)
    bolt14.Tieback.setOutofPlaneSpacing(1.5)
    bolt14.Tieback.setMaterialDependent(True)
    bolt14.Tieback.setBondStrengthCoefficient(1.6)
    bolt14.Tieback.setBondShearStiffnessCoefficient(1.7)
    bolt14.Tieback.setJointShear(True)
    bolt14.Tieback.setBoreholeDiameter(1.8)
    bolt14.Tieback.setPreTensioningForce(1.9)
    bolt14.Tieback.setConstantPretensioningForceInInstallStage(True)
    bolt14.Tieback.setFacePlates(True)
    bolt14.Tieback.setAddPullOutForce(False)
    bolt14.Tieback.setUseBondPercentageLength(False)
    bolt14.Tieback.setBondLength(1)
    bolt14.Tieback.setUseSecondaryBondLength(False)

    assert(bolt14.Tieback.getBoltDiameter(), 1.1)
    assert(bolt14.Tieback.getBoltModulusE(), 1.2)
    assert(bolt14.Tieback.getBoltModel(), BoltModels.P2_BOLT_PLASTIC)
    assert(bolt14.Tieback.getTensileCapacity(), 1.43) 
    assert(bolt14.Tieback.getResidualTensileCapacity(), 1.4)
    assert(bolt14.Tieback.getOutofPlaneSpacing(), 1.5)  
    assert(bolt14.Tieback.getMaterialDependent(), True)
    assert(bolt14.Tieback.getBondStrengthCoefficient(), 1.6)
    assert(bolt14.Tieback.getBondShearStiffnessCoefficient(), 1.7)
    assert(bolt14.Tieback.getJointShear(), True)
    assert(bolt14.Tieback.getBoreholeDiameter(), 1.8)
    assert(bolt14.Tieback.getPreTensioningForce(), 1.9)
    assert(bolt14.Tieback.getConstantPretensioningForceInInstallStage(), True)
    assert(bolt14.Tieback.getFacePlates(), True) 
    assert(bolt14.Tieback.getAddPullOutForce(), False)
    assert(bolt14.Tieback.getUseBondPercentageLength(), False)
    assert(bolt14.Tieback.getBondLength(), 1)
    assert(bolt14.Tieback.getSecondaryBondLength(), False)

def test15():
    bolt15.setBoltType(BoltTypes.TIEBACK_BOLT)
    bolt15.Tieback.setBoltDiameter(1.1)
    bolt15.Tieback.setBoltModulusE(1.2)
    bolt15.Tieback.setBoltModel(BoltModels.P2_BOLT_PLASTIC)
    bolt15.Tieback.setTensileCapacity(1.43)
    bolt15.Tieback.setResidualTensileCapacity(1.4)
    bolt15.Tieback.setOutofPlaneSpacing(1.5)
    bolt15.Tieback.setMaterialDependent(False)
    bolt15.Tieback.setBondShearStiffness(1.6)
    bolt15.Tieback.setBondStrength(1.7)
    bolt15.Tieback.setJointShear(False)
    bolt15.Tieback.setPreTensioningForce(1.9)
    bolt15.Tieback.setConstantPretensioningForceInInstallStage(False)
    bolt15.Tieback.setFacePlates(False)
    bolt15.Tieback.setAddPullOutForce(True)
    bolt15.Tieback.setPullOutForce(1.11)
    bolt15.Tieback.setUseBondPercentageLength(True)
    bolt15.Tieback.setPercentageBondLength(1)
    bolt15.Tieback.setUseSecondaryBondLength(True)
    bolt15.Tieback.setSecondaryBondLengthType(SecondaryBondLengthType.P2_BOLT_TIEBACK_SECONDARY_PERCENT)
    bolt15.Tieback.setPercentOfSecondaryBondLength(2)
    bolt15.Tieback.setDelayInstallAfterBolt(3)

    assert(bolt15.Tieback.getBoltDiameter(), 1.1)
    assert(bolt15.Tieback.getBoltModulusE(), 1.2)
    assert(bolt15.Tieback.getBoltModel(), BoltModels.P2_BOLT_PLASTIC)
    assert(bolt15.Tieback.getTensileCapacity(), 1.43) 
    assert(bolt15.Tieback.getResidualTensileCapacity(), 1.4)
    assert(bolt15.Tieback.getOutofPlaneSpacing(), 1.5)  
    assert(bolt15.Tieback.getMaterialDependent(), False)
    assert(bolt15.Tieback.getBondShearStiffness(), 1.6)
    assert(bolt15.Tieback.getBondStrength(), 1.7)
    assert(bolt15.Tieback.getJointShear(), False)
    assert(bolt15.Tieback.getPreTensioningForce(), 1.9)
    assert(bolt15.Tieback.getConstantPretensioningForceInInstallStage(), False)
    assert(bolt15.Tieback.getFacePlates(), False) 
    assert(bolt15.Tieback.getAddPullOutForce(), True)
    assert(bolt15.Tieback.getPullOutForce(), 1.11)
    assert(bolt15.Tieback.getUseBondPercentageLength(), True)
    assert(bolt15.Tieback.getPercentageBondLength(), 1)
    assert(bolt15.Tieback.getSecondaryBondLength(), True)
    assert(bolt15.Tieback.getSecondaryBondLengthType(), SecondaryBondLengthType.P2_BOLT_TIEBACK_SECONDARY_PERCENT)
    assert(bolt15.Tieback.getPercentOfSecondaryBondLength(), 2)
    assert(bolt15.Tieback.getDelayInstallAfterBolt(), 3)

def test16():
    bolt16.setBoltType(BoltTypes.TIEBACK_BOLT)
    bolt16.Tieback.setBoltDiameter(1.1)
    bolt16.Tieback.setBoltModulusE(1.2)
    bolt16.Tieback.setBoltModel(BoltModels.P2_BOLT_PLASTIC)
    bolt16.Tieback.setTensileCapacity(1.43)
    bolt16.Tieback.setResidualTensileCapacity(1.4)
    bolt16.Tieback.setOutofPlaneSpacing(1.5)
    bolt16.Tieback.setMaterialDependent(True)
    bolt16.Tieback.setBondStrengthCoefficient(1.6)
    bolt16.Tieback.setBondShearStiffnessCoefficient(1.7)
    bolt16.Tieback.setJointShear(True)
    bolt16.Tieback.setBoreholeDiameter(1.8)
    bolt16.Tieback.setPreTensioningForce(1.9)
    bolt16.Tieback.setConstantPretensioningForceInInstallStage(False)
    bolt16.Tieback.setFacePlates(False)
    bolt16.Tieback.setAddPullOutForce(True)
    bolt16.Tieback.setPullOutForce(1.11)
    bolt16.Tieback.setUseBondPercentageLength(True)
    bolt16.Tieback.setPercentageBondLength(1)
    bolt16.Tieback.setUseSecondaryBondLength(False)

    assert(bolt16.Tieback.getBoltDiameter(), 1.1)
    assert(bolt16.Tieback.getBoltModulusE(), 1.2)
    assert(bolt16.Tieback.getBoltModel(), BoltModels.P2_BOLT_PLASTIC)
    assert(bolt16.Tieback.getTensileCapacity(), 1.43) 
    assert(bolt16.Tieback.getResidualTensileCapacity(), 1.4)
    assert(bolt16.Tieback.getOutofPlaneSpacing(), 1.5)  
    assert(bolt16.Tieback.getMaterialDependent(), True)
    assert(bolt16.Tieback.getBondStrengthCoefficient(), 1.6)
    assert(bolt16.Tieback.getBondShearStiffnessCoefficient(), 1.7)
    assert(bolt16.Tieback.getJointShear(), True)
    assert(bolt16.Tieback.getBoreholeDiameter(), 1.8)
    assert(bolt16.Tieback.getPreTensioningForce(), 1.9)
    assert(bolt16.Tieback.getConstantPretensioningForceInInstallStage(), False)
    assert(bolt16.Tieback.getFacePlates(), False) 
    assert(bolt16.Tieback.getAddPullOutForce(), True)
    assert(bolt16.Tieback.getPullOutForce(), 1.11)
    assert(bolt16.Tieback.getUseBondPercentageLength(), True)
    assert(bolt16.Tieback.getPercentageBondLength(), 1)
    assert(bolt16.Tieback.getSecondaryBondLength(), False)

def test17():
    bolt17.setBoltType(BoltTypes.TIEBACK_BOLT)
    bolt17.Tieback.setBoltDiameter(1.1)
    bolt17.Tieback.setBoltModulusE(1.2)
    bolt17.Tieback.setBoltModel(BoltModels.P2_BOLT_ELASTIC)
    bolt17.Tieback.setOutofPlaneSpacing(1.3)
    bolt17.Tieback.setBondShearStiffness(1.4)
    bolt17.Tieback.setJointShear(True)
    bolt17.Tieback.setBoreholeDiameter(1.5)
    bolt17.Tieback.setPreTensioningForce(1.6)
    bolt17.Tieback.setConstantPretensioningForceInInstallStage(True)
    bolt17.Tieback.setFacePlates(True)
    bolt17.Tieback.setAddPullOutForce(True)
    bolt17.Tieback.setPullOutForce(1.7)
    bolt17.Tieback.setUseBondPercentageLength(True)
    bolt17.Tieback.setPercentageBondLength(1)
    bolt17.Tieback.setUseSecondaryBondLength(True)
    bolt17.Tieback.setSecondaryBondLengthType(SecondaryBondLengthType.P2_BOLT_TIEBACK_SECONDARY_PERCENT)
    bolt17.Tieback.setPercentOfSecondaryBondLength(2)
    bolt17.Tieback.setDelayInstallAfterBolt(3)

    assert(bolt17.Tieback.getBoltDiameter(), 1.1)
    assert(bolt17.Tieback.getBoltModulusE(), 1.2)
    assert(bolt17.Tieback.getBoltModel(), BoltModels.P2_BOLT_ELASTIC)
    assert(bolt17.Tieback.getOutofPlaneSpacing(), 1.3)
    assert(bolt17.Tieback.getBondShearStiffness(), 1.4)
    assert(bolt17.Tieback.getJointShear(), True)
    assert(bolt17.Tieback.getBoreholeDiameter(), 1.5)
    assert(bolt17.Tieback.getPreTensioningForce(), 1.6)
    assert(bolt17.Tieback.getConstantPretensioningForceInInstallStage(), True)
    assert(bolt17.Tieback.getFacePlates(), True) 
    assert(bolt17.Tieback.getAddPullOutForce(), True)
    assert(bolt17.Tieback.getPullOutForce(), 1.7)
    assert(bolt17.Tieback.getUseBondPercentageLength(), True)
    assert(bolt17.Tieback.getPercentageBondLength(), 1)
    assert(bolt17.Tieback.getSecondaryBondLength(), True)
    assert(bolt17.Tieback.getSecondaryBondLengthType(), SecondaryBondLengthType.P2_BOLT_TIEBACK_SECONDARY_PERCENT)
    assert(bolt17.Tieback.getPercentOfSecondaryBondLength(), 2)
    assert(bolt17.Tieback.getDelayInstallAfterBolt(), 3)

def test18():
    bolt18.setBoltType(BoltTypes.TIEBACK_BOLT)
    bolt18.Tieback.setBoltDiameter(1.1)
    bolt18.Tieback.setBoltModulusE(1.2)
    bolt18.Tieback.setBoltModel(BoltModels.P2_BOLT_ELASTIC)
    bolt18.Tieback.setOutofPlaneSpacing(1.3)
    bolt18.Tieback.setBondShearStiffness(1.4)
    bolt18.Tieback.setJointShear(False)
    bolt18.Tieback.setPreTensioningForce(1.6)
    bolt18.Tieback.setConstantPretensioningForceInInstallStage(False)
    bolt18.Tieback.setFacePlates(False)
    bolt18.Tieback.setAddPullOutForce(False)
    bolt18.Tieback.setUseBondPercentageLength(False)
    bolt18.Tieback.setBondLength(1)
    bolt18.Tieback.setUseSecondaryBondLength(False)

    assert(bolt18.Tieback.getBoltDiameter(), 1.1)
    assert(bolt18.Tieback.getBoltModulusE(), 1.2)
    assert(bolt18.Tieback.getBoltModel(), BoltModels.P2_BOLT_ELASTIC)
    assert(bolt18.Tieback.getOutofPlaneSpacing(), 1.3)
    assert(bolt18.Tieback.getBondShearStiffness(), 1.4)
    assert(bolt18.Tieback.getJointShear(), False)
    assert(bolt18.Tieback.getPreTensioningForce(), 1.6)
    assert(bolt18.Tieback.getConstantPretensioningForceInInstallStage(), False)
    assert(bolt18.Tieback.getFacePlates(), False) 
    assert(bolt18.Tieback.getAddPullOutForce(), False)
    assert(bolt18.Tieback.getUseBondPercentageLength(), False)
    assert(bolt18.Tieback.getBondLength(), 1)
    assert(bolt18.Tieback.getSecondaryBondLength(), False)

def test19():
    bolt19.setBoltType(BoltTypes.TIEBACK_BOLT)
    bolt19.Tieback.setBoltDiameter(1.1)
    bolt19.Tieback.setBoltModulusE(1.2)
    bolt19.Tieback.setBoltModel(BoltModels.P2_BOLT_ELASTIC)
    bolt19.Tieback.setOutofPlaneSpacing(1.3)
    bolt19.Tieback.setBondShearStiffness(1.4)
    bolt19.Tieback.setJointShear(True)
    bolt17.Tieback.setBoreholeDiameter(1.5)
    bolt19.Tieback.setPreTensioningForce(1.6)
    bolt19.Tieback.setConstantPretensioningForceInInstallStage(False)
    bolt19.Tieback.setFacePlates(False)
    bolt19.Tieback.setAddPullOutForce(False)
    bolt19.Tieback.setUseBondPercentageLength(False)
    bolt19.Tieback.setBondLength(1)
    bolt19.Tieback.setUseSecondaryBondLength(False)

    assert(bolt19.Tieback.getBoltDiameter(), 1.1)
    assert(bolt19.Tieback.getBoltModulusE(), 1.2)
    assert(bolt19.Tieback.getBoltModel(), BoltModels.P2_BOLT_ELASTIC)
    assert(bolt19.Tieback.getOutofPlaneSpacing(), 1.3)
    assert(bolt19.Tieback.getBondShearStiffness(), 1.4)
    assert(bolt19.Tieback.getJointShear(), True)
    assert(bolt17.Tieback.getBoreholeDiameter(), 1.5)
    assert(bolt19.Tieback.getPreTensioningForce(), 1.6)
    assert(bolt19.Tieback.getConstantPretensioningForceInInstallStage(), False)
    assert(bolt19.Tieback.getFacePlates(), False) 
    assert(bolt19.Tieback.getAddPullOutForce(), False)
    assert(bolt19.Tieback.getUseBondPercentageLength(), False)
    assert(bolt19.Tieback.getBondLength(), 1)
    assert(bolt19.Tieback.getSecondaryBondLength(), False)

def test20():
    bolt20.setBoltType(BoltTypes.TIEBACK_BOLT)
    bolt20.Tieback.setBoltDiameter(1.1)
    bolt20.Tieback.setBoltModulusE(1.2)
    bolt20.Tieback.setBoltModel(BoltModels.P2_BOLT_ELASTIC)
    bolt20.Tieback.setOutofPlaneSpacing(1.3)
    bolt20.Tieback.setBondShearStiffness(1.4)
    bolt20.Tieback.setJointShear(False)
    bolt20.Tieback.setPreTensioningForce(1.6)
    bolt20.Tieback.setConstantPretensioningForceInInstallStage(True)
    bolt20.Tieback.setFacePlates(False)
    bolt20.Tieback.setAddPullOutForce(False)
    bolt20.Tieback.setUseBondPercentageLength(False)
    bolt20.Tieback.setBondLength(1)
    bolt20.Tieback.setUseSecondaryBondLength(False)

    assert(bolt20.Tieback.getBoltDiameter(), 1.1)
    assert(bolt20.Tieback.getBoltModulusE(), 1.2)
    assert(bolt20.Tieback.getBoltModel(), BoltModels.P2_BOLT_ELASTIC)
    assert(bolt20.Tieback.getOutofPlaneSpacing(), 1.3)
    assert(bolt20.Tieback.getBondShearStiffness(), 1.4)
    assert(bolt20.Tieback.getJointShear(), False)
    assert(bolt20.Tieback.getPreTensioningForce(), 1.6)
    assert(bolt20.Tieback.getConstantPretensioningForceInInstallStage(), True)
    assert(bolt20.Tieback.getFacePlates(), False) 
    assert(bolt20.Tieback.getAddPullOutForce(), False)
    assert(bolt20.Tieback.getUseBondPercentageLength(), False)
    assert(bolt20.Tieback.getBondLength(), 1)
    assert(bolt20.Tieback.getSecondaryBondLength(), False)

def test21():
    bolt21.setBoltType(BoltTypes.TIEBACK_BOLT)
    bolt21.Tieback.setBoltDiameter(1.1)
    bolt21.Tieback.setBoltModulusE(1.2)
    bolt21.Tieback.setBoltModel(BoltModels.P2_BOLT_ELASTIC)
    bolt21.Tieback.setOutofPlaneSpacing(1.3)
    bolt21.Tieback.setBondShearStiffness(1.4)
    bolt21.Tieback.setJointShear(False)
    bolt21.Tieback.setPreTensioningForce(1.6)
    bolt21.Tieback.setConstantPretensioningForceInInstallStage(False)
    bolt21.Tieback.setFacePlates(True)
    bolt21.Tieback.setAddPullOutForce(False)
    bolt21.Tieback.setUseBondPercentageLength(False)
    bolt21.Tieback.setBondLength(1)
    bolt21.Tieback.setUseSecondaryBondLength(False)

    assert(bolt21.Tieback.getBoltDiameter(), 1.1)
    assert(bolt21.Tieback.getBoltModulusE(), 1.2)
    assert(bolt21.Tieback.getBoltModel(), BoltModels.P2_BOLT_ELASTIC)
    assert(bolt21.Tieback.getOutofPlaneSpacing(), 1.3)
    assert(bolt21.Tieback.getBondShearStiffness(), 1.4)
    assert(bolt21.Tieback.getJointShear(), False)
    assert(bolt21.Tieback.getPreTensioningForce(), 1.6)
    assert(bolt21.Tieback.getConstantPretensioningForceInInstallStage(), False)
    assert(bolt21.Tieback.getFacePlates(), True) 
    assert(bolt21.Tieback.getAddPullOutForce(), False)
    assert(bolt21.Tieback.getUseBondPercentageLength(), False)
    assert(bolt21.Tieback.getBondLength(), 1)
    assert(bolt21.Tieback.getSecondaryBondLength(), False)

def test22():
    bolt22.setBoltType(BoltTypes.TIEBACK_BOLT)
    bolt22.Tieback.setBoltDiameter(1.1)
    bolt22.Tieback.setBoltModulusE(1.2)
    bolt22.Tieback.setBoltModel(BoltModels.P2_BOLT_ELASTIC)
    bolt22.Tieback.setOutofPlaneSpacing(1.3)
    bolt22.Tieback.setBondShearStiffness(1.4)
    bolt22.Tieback.setJointShear(False)
    bolt22.Tieback.setPreTensioningForce(1.6)
    bolt22.Tieback.setConstantPretensioningForceInInstallStage(False)
    bolt22.Tieback.setFacePlates(False)
    bolt22.Tieback.setAddPullOutForce(True)
    bolt22.Tieback.setPullOutForce(1.7)
    bolt22.Tieback.setUseBondPercentageLength(False)
    bolt22.Tieback.setBondLength(1)
    bolt22.Tieback.setUseSecondaryBondLength(False)

    assert(bolt22.Tieback.getBoltDiameter(), 1.1)
    assert(bolt22.Tieback.getBoltModulusE(), 1.2)
    assert(bolt22.Tieback.getBoltModel(), BoltModels.P2_BOLT_ELASTIC)
    assert(bolt22.Tieback.getOutofPlaneSpacing(), 1.3)
    assert(bolt22.Tieback.getBondShearStiffness(), 1.4)
    assert(bolt22.Tieback.getJointShear(), False)
    assert(bolt22.Tieback.getPreTensioningForce(), 1.6)
    assert(bolt22.Tieback.getConstantPretensioningForceInInstallStage(), False)
    assert(bolt22.Tieback.getFacePlates(), False) 
    assert(bolt22.Tieback.getAddPullOutForce(), True)
    assert(bolt22.Tieback.getPullOutForce(), 1.7)
    assert(bolt22.Tieback.getUseBondPercentageLength(), False)
    assert(bolt22.Tieback.getBondLength(), 1)
    assert(bolt22.Tieback.getSecondaryBondLength(), False)

def test23():
    bolt23.setBoltType(BoltTypes.TIEBACK_BOLT)
    bolt23.Tieback.setBoltDiameter(1.1)
    bolt23.Tieback.setBoltModulusE(1.2)
    bolt23.Tieback.setBoltModel(BoltModels.P2_BOLT_ELASTIC)
    bolt23.Tieback.setOutofPlaneSpacing(1.3)
    bolt23.Tieback.setBondShearStiffness(1.4)
    bolt23.Tieback.setJointShear(False)
    bolt23.Tieback.setPreTensioningForce(1.6)
    bolt23.Tieback.setConstantPretensioningForceInInstallStage(False)
    bolt23.Tieback.setFacePlates(False)
    bolt23.Tieback.setAddPullOutForce(False)
    bolt23.Tieback.setUseBondPercentageLength(True)
    bolt23.Tieback.setPercentageBondLength(1)
    bolt23.Tieback.setUseSecondaryBondLength(False)

    assert(bolt23.Tieback.getBoltDiameter(), 1.1)
    assert(bolt23.Tieback.getBoltModulusE(), 1.2)
    assert(bolt23.Tieback.getBoltModel(), BoltModels.P2_BOLT_ELASTIC)
    assert(bolt23.Tieback.getOutofPlaneSpacing(), 1.3)
    assert(bolt23.Tieback.getBondShearStiffness(), 1.4)
    assert(bolt23.Tieback.getJointShear(), False)
    assert(bolt23.Tieback.getPreTensioningForce(), 1.6)
    assert(bolt23.Tieback.getConstantPretensioningForceInInstallStage(), False)
    assert(bolt23.Tieback.getFacePlates(), False) 
    assert(bolt23.Tieback.getAddPullOutForce(), False)
    assert(bolt23.Tieback.getUseBondPercentageLength(), True)
    assert(bolt23.Tieback.getPercentageBondLength(), 1)
    assert(bolt23.Tieback.getSecondaryBondLength(), False)

def test24():
    bolt24.setBoltType(BoltTypes.TIEBACK_BOLT)
    bolt24.Tieback.setBoltDiameter(1.1)
    bolt24.Tieback.setBoltModulusE(1.2)
    bolt24.Tieback.setBoltModel(BoltModels.P2_BOLT_ELASTIC)
    bolt24.Tieback.setOutofPlaneSpacing(1.3)
    bolt24.Tieback.setBondShearStiffness(1.4)
    bolt24.Tieback.setJointShear(False)
    bolt24.Tieback.setPreTensioningForce(1.6)
    bolt24.Tieback.setConstantPretensioningForceInInstallStage(False)
    bolt24.Tieback.setFacePlates(False)
    bolt24.Tieback.setAddPullOutForce(False)
    bolt24.Tieback.setUseBondPercentageLength(False)
    bolt24.Tieback.setBondLength(1)
    bolt24.Tieback.setUseSecondaryBondLength(False)

    assert(bolt24.Tieback.getBoltDiameter(), 1.1)
    assert(bolt24.Tieback.getBoltModulusE(), 1.2)
    assert(bolt24.Tieback.getBoltModel(), BoltModels.P2_BOLT_ELASTIC)
    assert(bolt24.Tieback.getOutofPlaneSpacing(), 1.3)
    assert(bolt24.Tieback.getBondShearStiffness(), 1.4)
    assert(bolt24.Tieback.getJointShear(), False)
    assert(bolt24.Tieback.getPreTensioningForce(), 1.6)
    assert(bolt24.Tieback.getConstantPretensioningForceInInstallStage(), False)
    assert(bolt24.Tieback.getFacePlates(), False) 
    assert(bolt24.Tieback.getAddPullOutForce(), False)
    assert(bolt24.Tieback.getUseBondPercentageLength(), False)
    assert(bolt24.Tieback.getBondLength(), 1)
    assert(bolt24.Tieback.getSecondaryBondLength(), False)

def test25():
    bolt25.setBoltType(BoltTypes.TIEBACK_BOLT)
    bolt25.Tieback.setBoltDiameter(1.1)
    bolt25.Tieback.setBoltModulusE(1.2)
    bolt25.Tieback.setBoltModel(BoltModels.P2_BOLT_ELASTIC)
    bolt25.Tieback.setOutofPlaneSpacing(1.3)
    bolt25.Tieback.setBondShearStiffness(1.4)
    bolt25.Tieback.setJointShear(True)
    bolt25.Tieback.setBoreholeDiameter(1.5)
    bolt25.Tieback.setPreTensioningForce(1.6)
    bolt25.Tieback.setConstantPretensioningForceInInstallStage(False)
    bolt25.Tieback.setFacePlates(True)
    bolt25.Tieback.setAddPullOutForce(False)
    bolt25.Tieback.setUseBondPercentageLength(True)
    bolt25.Tieback.setPercentageBondLength(1)
    bolt25.Tieback.setUseSecondaryBondLength(False)

    assert(bolt25.Tieback.getBoltDiameter(), 1.1)
    assert(bolt25.Tieback.getBoltModulusE(), 1.2)
    assert(bolt25.Tieback.getBoltModel(), BoltModels.P2_BOLT_ELASTIC)
    assert(bolt25.Tieback.getOutofPlaneSpacing(), 1.3)
    assert(bolt25.Tieback.getBondShearStiffness(), 1.4)
    assert(bolt25.Tieback.getJointShear(), True)
    assert(bolt25.Tieback.getBoreholeDiameter(), 1.5)
    assert(bolt25.Tieback.getPreTensioningForce(), 1.6)
    assert(bolt25.Tieback.getConstantPretensioningForceInInstallStage(), False)
    assert(bolt25.Tieback.getFacePlates(), True) 
    assert(bolt25.Tieback.getAddPullOutForce(), False)
    assert(bolt25.Tieback.getUseBondPercentageLength(), True)
    assert(bolt25.Tieback.getPercentageBondLength(), 1)
    assert(bolt25.Tieback.getSecondaryBondLength(), False)

def test26():
    bolt26.setBoltType(BoltTypes.TIEBACK_BOLT)
    bolt26.Tieback.setBoltDiameter(1.1)
    bolt26.Tieback.setBoltModulusE(1.2)
    bolt26.Tieback.setBoltModel(BoltModels.P2_BOLT_ELASTIC)
    bolt26.Tieback.setOutofPlaneSpacing(1.3)
    bolt26.Tieback.setBondShearStiffness(1.4)
    bolt26.Tieback.setJointShear(False)
    bolt26.Tieback.setPreTensioningForce(1.6)
    bolt26.Tieback.setConstantPretensioningForceInInstallStage(True)
    bolt26.Tieback.setFacePlates(False)
    bolt26.Tieback.setAddPullOutForce(True)
    bolt26.Tieback.setPullOutForce(1.7)
    bolt26.Tieback.setUseBondPercentageLength(False)
    bolt26.Tieback.setBondLength(1)
    bolt26.Tieback.setUseSecondaryBondLength(True)
    bolt26.Tieback.setSecondaryBondLengthType(SecondaryBondLengthType.P2_BOLT_TIEBACK_SECONDARY_PERCENT)
    bolt26.Tieback.setPercentOfSecondaryBondLength(2)
    bolt26.Tieback.setDelayInstallAfterBolt(3)

    assert(bolt26.Tieback.getBoltDiameter(), 1.1)
    assert(bolt26.Tieback.getBoltModulusE(), 1.2)
    assert(bolt26.Tieback.getBoltModel(), BoltModels.P2_BOLT_ELASTIC)
    assert(bolt26.Tieback.getOutofPlaneSpacing(), 1.3)
    assert(bolt26.Tieback.getBondShearStiffness(), 1.4)
    assert(bolt26.Tieback.getJointShear(), False)
    assert(bolt26.Tieback.getPreTensioningForce(), 1.6)
    assert(bolt26.Tieback.getConstantPretensioningForceInInstallStage(), True)
    assert(bolt26.Tieback.getFacePlates(), False) 
    assert(bolt26.Tieback.getAddPullOutForce(), True)
    assert(bolt26.Tieback.getPullOutForce(), 1.7)
    assert(bolt26.Tieback.getUseBondPercentageLength(), False)
    assert(bolt26.Tieback.getBondLength(), 1)
    assert(bolt26.Tieback.getSecondaryBondLength(), True)
    assert(bolt26.Tieback.getSecondaryBondLengthType(), SecondaryBondLengthType.P2_BOLT_TIEBACK_SECONDARY_PERCENT)
    assert(bolt26.Tieback.getPercentOfSecondaryBondLength(), 2)
    assert(bolt26.Tieback.getDelayInstallAfterBolt(), 3)

def test27():
    bolt27.setBoltType(BoltTypes.TIEBACK_BOLT)
    bolt27.Tieback.setBoltDiameter(1.1)
    bolt27.Tieback.setBoltModulusE(1.2)
    bolt27.Tieback.setBoltModel(BoltModels.P2_BOLT_ELASTIC)
    bolt27.Tieback.setOutofPlaneSpacing(1.3)
    bolt27.Tieback.setBondShearStiffness(1.4)
    bolt27.Tieback.setJointShear(True)
    bolt27.Tieback.setBoreholeDiameter(1.5)
    bolt27.Tieback.setPreTensioningForce(1.6)
    bolt27.Tieback.setConstantPretensioningForceInInstallStage(True)
    bolt27.Tieback.setFacePlates(True)
    bolt27.Tieback.setAddPullOutForce(False)
    bolt27.Tieback.setUseBondPercentageLength(False)
    bolt27.Tieback.setBondLength(1)
    bolt27.Tieback.setUseSecondaryBondLength(False)

    assert(bolt27.Tieback.getBoltDiameter(), 1.1)
    assert(bolt27.Tieback.getBoltModulusE(), 1.2)
    assert(bolt27.Tieback.getBoltModel(), BoltModels.P2_BOLT_ELASTIC)
    assert(bolt27.Tieback.getOutofPlaneSpacing(), 1.3)
    assert(bolt27.Tieback.getBondShearStiffness(), 1.4)
    assert(bolt27.Tieback.getJointShear(), True)
    assert(bolt27.Tieback.getBoreholeDiameter(), 1.5)
    assert(bolt27.Tieback.getPreTensioningForce(), 1.6)
    assert(bolt27.Tieback.getConstantPretensioningForceInInstallStage(), True)
    assert(bolt27.Tieback.getFacePlates(), True) 
    assert(bolt27.Tieback.getAddPullOutForce(), False)
    assert(bolt27.Tieback.getUseBondPercentageLength(), False)
    assert(bolt27.Tieback.getBondLength(), 1)
    assert(bolt27.Tieback.getSecondaryBondLength(), False)

def test28():
    bolt28.setBoltType(BoltTypes.TIEBACK_BOLT)
    bolt28.Tieback.setBoltDiameter(1.1)
    bolt28.Tieback.setBoltModulusE(1.2)
    bolt28.Tieback.setBoltModel(BoltModels.P2_BOLT_ELASTIC)
    bolt28.Tieback.setOutofPlaneSpacing(1.3)
    bolt28.Tieback.setBondShearStiffness(1.4)
    bolt28.Tieback.setJointShear(False)
    bolt28.Tieback.setPreTensioningForce(1.6)
    bolt28.Tieback.setConstantPretensioningForceInInstallStage(False)
    bolt28.Tieback.setFacePlates(False)
    bolt28.Tieback.setAddPullOutForce(True)
    bolt28.Tieback.setPullOutForce(1.7)
    bolt28.Tieback.setUseBondPercentageLength(True)
    bolt28.Tieback.setPercentageBondLength(1)
    bolt28.Tieback.setUseSecondaryBondLength(True)
    bolt28.Tieback.setSecondaryBondLengthType(SecondaryBondLengthType.P2_BOLT_TIEBACK_SECONDARY_PERCENT)
    bolt28.Tieback.setPercentOfSecondaryBondLength(2)
    bolt28.Tieback.setDelayInstallAfterBolt(3)

    assert(bolt28.Tieback.getBoltDiameter(), 1.1)
    assert(bolt28.Tieback.getBoltModulusE(), 1.2)
    assert(bolt28.Tieback.getBoltModel(), BoltModels.P2_BOLT_ELASTIC)
    assert(bolt28.Tieback.getOutofPlaneSpacing(), 1.3)
    assert(bolt28.Tieback.getBondShearStiffness(), 1.4)
    assert(bolt28.Tieback.getJointShear(), False)
    assert(bolt28.Tieback.getPreTensioningForce(), 1.6)
    assert(bolt28.Tieback.getConstantPretensioningForceInInstallStage(), False)
    assert(bolt28.Tieback.getFacePlates(), False) 
    assert(bolt28.Tieback.getAddPullOutForce(), True)
    assert(bolt28.Tieback.getPullOutForce(), 1.7)
    assert(bolt28.Tieback.getUseBondPercentageLength(), True)
    assert(bolt28.Tieback.getPercentageBondLength(), 1)
    assert(bolt28.Tieback.getSecondaryBondLength(), True)
    assert(bolt28.Tieback.getSecondaryBondLengthType(), SecondaryBondLengthType.P2_BOLT_TIEBACK_SECONDARY_PERCENT)
    assert(bolt28.Tieback.getPercentOfSecondaryBondLength(), 2)
    assert(bolt28.Tieback.getDelayInstallAfterBolt(), 3)

def test29():
    bolt29.setBoltType(BoltTypes.TIEBACK_BOLT)
    bolt29.Tieback.setBoltDiameter(1.1)
    bolt29.Tieback.setBoltModulusE(1.2)
    bolt29.Tieback.setBoltModel(BoltModels.P2_BOLT_ELASTIC)
    bolt29.Tieback.setOutofPlaneSpacing(1.3)
    bolt29.Tieback.setBondShearStiffness(1.4)
    bolt29.Tieback.setJointShear(True)
    bolt29.Tieback.setBoreholeDiameter(1.5)
    bolt29.Tieback.setPreTensioningForce(1.6)
    bolt29.Tieback.setConstantPretensioningForceInInstallStage(True)
    bolt29.Tieback.setFacePlates(False)
    bolt29.Tieback.setAddPullOutForce(False)
    bolt29.Tieback.setUseBondPercentageLength(True)
    bolt29.Tieback.setPercentageBondLength(1)
    bolt29.Tieback.setUseSecondaryBondLength(True)
    bolt29.Tieback.setSecondaryBondLengthType(SecondaryBondLengthType.P2_BOLT_TIEBACK_SECONDARY_PERCENT)
    bolt29.Tieback.setPercentOfSecondaryBondLength(2)
    bolt29.Tieback.setDelayInstallAfterBolt(3)

    assert(bolt29.Tieback.getBoltDiameter(), 1.1)
    assert(bolt29.Tieback.getBoltModulusE(), 1.2)
    assert(bolt29.Tieback.getBoltModel(), BoltModels.P2_BOLT_ELASTIC)
    assert(bolt29.Tieback.getOutofPlaneSpacing(), 1.3)
    assert(bolt29.Tieback.getBondShearStiffness(), 1.4)
    assert(bolt29.Tieback.getJointShear(), True)
    assert(bolt29.Tieback.getBoreholeDiameter(), 1.5)
    assert(bolt29.Tieback.getPreTensioningForce(), 1.6)
    assert(bolt29.Tieback.getConstantPretensioningForceInInstallStage(), True)
    assert(bolt29.Tieback.getFacePlates(), False) 
    assert(bolt29.Tieback.getAddPullOutForce(), False)
    assert(bolt29.Tieback.getUseBondPercentageLength(), True)
    assert(bolt29.Tieback.getPercentageBondLength(), 1)
    assert(bolt29.Tieback.getSecondaryBondLength(), True)
    assert(bolt29.Tieback.getSecondaryBondLengthType(), SecondaryBondLengthType.P2_BOLT_TIEBACK_SECONDARY_PERCENT)
    assert(bolt29.Tieback.getPercentOfSecondaryBondLength(), 2)
    assert(bolt29.Tieback.getDelayInstallAfterBolt(), 3)

test1()
test2()
test3()
test4()
test5()
test6()
test7()
test8()
test9()
test10()
test11()
test12()
test13()
test14()
test15()
test16()
test17()
test18()
test19()
test20()
test21()
test22()
test23()
test24()
test25()
test26()
test27() 
test28()
test29()

model.save()

pass